/**
 * Bedroom Rules - 次卧/儿童房规则
 * 
 * 涵盖：床位、学习、睡眠、成长、采光、通风、收纳、空间利用
 */

import type { FengShuiRule, FengShuiContext } from '../../types'

export const BEDROOM_RULES: FengShuiRule[] = [
  {
    id: 'bedroom-bed-position',
    name: '床位合理',
    category: 'bed',
    applicableTo: ['bedroom'],
    source: ['阳宅三要', '现代风水'],
    heritage: 'both',
    priority: 85,
    weight: 80,
    confidence: 85,
    referenceIds: ['yzsy-007'],
    tags: ['卧室', '床', '吉'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => {
      const bedroom = ctx.rooms.find(r => r.roomType === 'bedroom')
      return !!(bedroom && bedroom.score > 65)
    },
    result: {
      type: 'auspicious',
      score: 80,
      tags: ['吉'],
    },
    impact: { health: 4, sleep: 5, study: 2 },
    improvement: '床头靠墙，床不对门',
  },
  {
    id: 'bedroom-good-lighting',
    name: '卧室采光适中',
    category: 'bed',
    applicableTo: ['bedroom'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 70,
    weight: 65,
    confidence: 85,
    referenceIds: ['xd-020'],
    tags: ['卧室', '采光', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 70,
      tags: ['平'],
    },
    impact: { health: 3, sleep: 4 },
    improvement: '使用遮光窗帘调节光线',
  },
  {
    id: 'bedroom-tidy',
    name: '卧室整洁',
    category: 'bed',
    applicableTo: ['bedroom'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 65,
    weight: 60,
    confidence: 80,
    referenceIds: ['xd-021'],
    tags: ['卧室', '整洁', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 70,
      tags: ['吉'],
    },
    impact: { health: 3, sleep: 3 },
    improvement: '保持卧室整洁',
  },
  {
    id: 'bedroom-good-ventilation',
    name: '卧室通风良好',
    category: 'bed',
    applicableTo: ['bedroom'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 70,
    weight: 65,
    confidence: 85,
    referenceIds: ['xd-022'],
    tags: ['卧室', '通风', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 75,
      tags: ['吉'],
    },
    impact: { health: 4, sleep: 3 },
    improvement: '保持空气流通',
  },
  {
    id: 'bedroom-headboard-not-against-window',
    name: '床头不靠窗',
    category: 'bed',
    applicableTo: ['bedroom'],
    source: ['阳宅三要', '现代风水'],
    heritage: 'both',
    priority: 80,
    weight: 75,
    confidence: 85,
    referenceIds: ['yzsy-023', 'xd-025'],
    tags: ['卧室', '床头', '靠窗', '凶'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'inauspicious',
      score: 55,
      tags: ['凶'],
    },
    impact: { sleep: -5, health: -4, relationship: -2 },
    improvement: '床头靠墙摆放，避免靠窗',
  },
  {
    id: 'bedroom-bed-not-facing-door',
    name: '床不冲门',
    category: 'bed',
    applicableTo: ['bedroom'],
    source: ['阳宅三要', '八宅明镜'],
    heritage: 'classical',
    priority: 85,
    weight: 80,
    confidence: 90,
    referenceIds: ['yzsy-024', 'bzmj-009'],
    tags: ['卧室', '床', '冲门', '凶'],
    schools: ['bazhai', 'xuankong'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'inauspicious',
      score: 50,
      tags: ['凶'],
    },
    impact: { sleep: -5, health: -4, relationship: -3 },
    improvement: '调整床位，避免床正对卧室门',
  },
  {
    id: 'bedroom-no-beam-press',
    name: '卧室无横梁压床',
    category: 'bed',
    applicableTo: ['bedroom'],
    source: ['阳宅三要', '八宅明镜'],
    heritage: 'classical',
    priority: 82,
    weight: 78,
    confidence: 88,
    referenceIds: ['yzsy-025', 'bzmj-010'],
    tags: ['卧室', '横梁', '压床', '凶'],
    schools: ['bazhai', 'xuankong'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'inauspicious',
      score: 52,
      tags: ['凶'],
    },
    impact: { sleep: -5, health: -5, relationship: -3 },
    improvement: '吊顶遮挡横梁，或调整床的位置避开横梁',
  },
  {
    id: 'bedroom-under-bed-tidy',
    name: '床底整洁',
    category: 'bed',
    applicableTo: ['bedroom'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 68,
    weight: 63,
    confidence: 78,
    referenceIds: ['xd-026'],
    tags: ['卧室', '床底', '整洁', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 72,
      tags: ['吉'],
    },
    impact: { health: 3, sleep: 4, wealth: 2 },
    improvement: '保持床底清洁，不堆放杂物',
  },
]
