/**
 * Dining Room Rules - 餐厅规则
 * 
 * 涵盖：餐桌位置、餐桌形状、灯光、聚气、动线、家庭关系
 */

import type { FengShuiRule, FengShuiContext } from '../../types'

export const DINING_ROOM_RULES: FengShuiRule[] = [
  {
    id: 'dining-table-position',
    name: '餐桌位置合理',
    category: 'dining',
    applicableTo: ['dining'],
    source: ['阳宅三要', '现代风水'],
    heritage: 'both',
    priority: 75,
    weight: 70,
    confidence: 80,
    referenceIds: ['yzsy-019'],
    tags: ['餐厅', '餐桌', '位置'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 70,
      tags: ['平'],
    },
    impact: { health: 3, relationship: 4, wealth: 2 },
    improvement: '餐桌放在餐厅中心位置',
  },
  {
    id: 'dining-round-table',
    name: '餐桌圆形为佳',
    category: 'dining',
    applicableTo: ['dining'],
    source: ['阳宅三要'],
    heritage: 'classical',
    priority: 70,
    weight: 65,
    confidence: 75,
    referenceIds: ['yzsy-020'],
    tags: ['餐厅', '餐桌', '形状', '吉'],
    schools: ['bazhai'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 70,
      tags: ['平'],
    },
    impact: { relationship: 4, health: 2 },
    improvement: '圆形餐桌象征团圆圆满',
  },
  {
    id: 'dining-good-lighting',
    name: '餐厅光线充足',
    category: 'dining',
    applicableTo: ['dining'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 70,
    weight: 65,
    confidence: 80,
    referenceIds: ['xd-016'],
    tags: ['餐厅', '采光', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 75,
      tags: ['吉'],
    },
    impact: { health: 3, relationship: 3 },
    improvement: '餐厅保持明亮',
  },
  {
    id: 'dining-tidy',
    name: '餐厅整洁',
    category: 'dining',
    applicableTo: ['dining'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 65,
    weight: 60,
    confidence: 80,
    referenceIds: ['xd-017'],
    tags: ['餐厅', '整洁', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 70,
      tags: ['吉'],
    },
    impact: { health: 3, relationship: 2 },
    improvement: '餐后及时清理',
  },
  {
    id: 'dining-not-adjacent-kitchen',
    name: '餐厅不靠厨房',
    category: 'dining',
    applicableTo: ['dining'],
    source: ['阳宅三要', '现代风水'],
    heritage: 'both',
    priority: 72,
    weight: 68,
    confidence: 75,
    referenceIds: ['yzsy-026', 'xd-027'],
    tags: ['餐厅', '厨房', '油烟', '凶'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'warning',
      score: 62,
      tags: ['警示'],
    },
    impact: { health: -4, wealth: -2 },
    improvement: '餐厅与厨房保持距离，或设置隔断屏风',
  },
  {
    id: 'dining-not-adjacent-bathroom',
    name: '餐厅不靠卫生间',
    category: 'dining',
    applicableTo: ['dining'],
    source: ['阳宅三要', '现代风水'],
    heritage: 'both',
    priority: 78,
    weight: 73,
    confidence: 82,
    referenceIds: ['yzsy-027', 'xd-028'],
    tags: ['餐厅', '卫生间', '污秽', '凶'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'inauspicious',
      score: 55,
      tags: ['凶'],
    },
    impact: { health: -5, wealth: -3, relationship: -2 },
    improvement: '餐厅避开卫生间，或常关卫生间门',
  },
  {
    id: 'dining-table-no-beam-press',
    name: '餐桌不压梁',
    category: 'dining',
    applicableTo: ['dining'],
    source: ['阳宅三要', '八宅明镜'],
    heritage: 'classical',
    priority: 75,
    weight: 70,
    confidence: 80,
    referenceIds: ['yzsy-028', 'bzmj-011'],
    tags: ['餐厅', '餐桌', '横梁', '凶'],
    schools: ['bazhai', 'xuankong'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'inauspicious',
      score: 58,
      tags: ['凶'],
    },
    impact: { health: -4, relationship: -3, wealth: -2 },
    improvement: '吊顶遮挡横梁，或调整餐桌位置避开横梁',
  },
  {
    id: 'dining-has-back-support',
    name: '餐厅有靠山',
    category: 'dining',
    applicableTo: ['dining'],
    source: ['阳宅三要', '现代风水'],
    heritage: 'both',
    priority: 70,
    weight: 65,
    confidence: 75,
    referenceIds: ['yzsy-029', 'xd-029'],
    tags: ['餐厅', '靠山', '吉'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 73,
      tags: ['吉'],
    },
    impact: { relationship: 4, wealth: 3, health: 2 },
    improvement: '餐厅靠墙，象征家庭有靠、财运稳定',
  },
]
