/**
 * Entrance Rules - 玄关规则
 * 
 * 涵盖：开门见厅、开门见灶、开门见厕、玄关聚气、鞋柜、采光、通风、尺寸、植物、
 *       碰壁煞、楼梯冲门、玄关大小、鞋柜高度、镜子对门、杂物堆积
 */

import type { FengShuiRule, FengShuiContext } from '../../types'

export const ENTRANCE_RULES: FengShuiRule[] = [
  {
    id: 'entrance-has-vestibule',
    name: '玄关有缓冲',
    category: 'door',
    applicableTo: ['entrance'],
    source: ['阳宅三要', '现代风水'],
    heritage: 'both',
    priority: 90,
    weight: 85,
    confidence: 90,
    referenceIds: ['yzsy-003'],
    tags: ['玄关', '聚气', '吉'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => {
      if (!ctx.spatial) return false
      const doors = ctx.spatial.doors || []
      const hasMainEntrance = doors.some((d: any) => d.type === 'main-entrance')
      return hasMainEntrance
    },
    result: {
      type: 'auspicious',
      score: 85,
      tags: ['吉'],
    },
    impact: { wealth: 5, career: 3 },
    improvement: '设置玄关柜或屏风',
  },
  {
    id: 'entrance-no-kitchen-direct',
    name: '开门不见灶',
    category: 'kitchen',
    applicableTo: ['entrance'],
    source: ['阳宅三要', '阳宅十书'],
    heritage: 'classical',
    priority: 85,
    weight: 80,
    confidence: 85,
    referenceIds: ['yzsy-006', 'yzsx-005'],
    tags: ['玄关', '开门见灶', '凶'],
    schools: ['bazhai'],
    condition: (ctx: FengShuiContext) => {
      if (!ctx.spatial) return true
      const sha = ctx.spatial.spatialSha || []
      return !sha.some((s: any) => s.type === 'men-chong-zao')
    },
    result: {
      type: 'auspicious',
      score: 80,
      tags: ['吉'],
    },
    impact: { wealth: 4, health: 2 },
    improvement: '设置玄关遮挡',
  },
  {
    id: 'entrance-no-bathroom-direct',
    name: '开门不见厕',
    category: 'bathroom',
    applicableTo: ['entrance'],
    source: ['阳宅三要'],
    heritage: 'classical',
    priority: 80,
    weight: 75,
    confidence: 85,
    referenceIds: ['yzsy-010'],
    tags: ['玄关', '开门见厕', '凶'],
    schools: ['bazhai', 'xuankong'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 70,
      tags: ['平'],
    },
    impact: { health: 3, wealth: -2 },
    improvement: '设置玄关或门帘',
  },
  {
    id: 'entrance-no-mirror',
    name: '玄关不对镜',
    category: 'door',
    applicableTo: ['entrance'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 75,
    weight: 70,
    confidence: 80,
    referenceIds: ['xd-001'],
    tags: ['玄关', '镜子', '凶'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 70,
      tags: ['平'],
    },
    impact: { wealth: -2 },
    improvement: '调整镜子位置',
  },
  {
    id: 'entrance-good-lighting',
    name: '玄关采光充足',
    category: 'door',
    applicableTo: ['entrance'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 70,
    weight: 65,
    confidence: 85,
    referenceIds: ['xd-002'],
    tags: ['玄关', '采光', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 75,
      tags: ['吉'],
    },
    impact: { wealth: 3, career: 2 },
    improvement: '增加照明',
  },
  {
    id: 'entrance-tidy',
    name: '玄关整洁',
    category: 'door',
    applicableTo: ['entrance'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 65,
    weight: 60,
    confidence: 80,
    referenceIds: ['xd-003'],
    tags: ['玄关', '整洁', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 70,
      tags: ['吉'],
    },
    impact: { wealth: 2, career: 2 },
    improvement: '保持整洁，定期清理',
  },
  {
    id: 'entrance-wall-block',
    name: '开门见墙（碰壁煞）',
    category: 'entrance',
    applicableTo: ['entrance'],
    source: ['阳宅三要', '黄帝宅经'],
    heritage: 'classical',
    priority: 88,
    weight: 85,
    confidence: 88,
    referenceIds: ['yzsy-015', 'hdzj-008'],
    tags: ['玄关', '碰壁煞', '凶'],
    schools: ['bazhai', 'xuankong'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'inauspicious',
      score: 40,
      tags: ['凶'],
    },
    impact: { career: -5, wealth: -3 },
    improvement: '移开遮挡物或设置玄关引导气流',
  },
  {
    id: 'entrance-stair-chong',
    name: '开门见梯（楼梯冲门）',
    category: 'entrance',
    applicableTo: ['entrance'],
    source: ['阳宅十书', '现代风水'],
    heritage: 'both',
    priority: 85,
    weight: 80,
    confidence: 85,
    referenceIds: ['yzsx-012', 'xd-015'],
    tags: ['玄关', '楼梯冲门', '凶'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'inauspicious',
      score: 45,
      tags: ['凶'],
    },
    impact: { wealth: -5, health: -2, career: -3 },
    improvement: '设置屏风、玄关柜或悬挂珠帘化解',
  },
  {
    id: 'entrance-size-proper',
    name: '玄关大小适中',
    category: 'entrance',
    applicableTo: ['entrance'],
    source: ['黄帝宅经', '现代风水'],
    heritage: 'both',
    priority: 75,
    weight: 70,
    confidence: 82,
    referenceIds: ['hdzj-012', 'xd-020'],
    tags: ['玄关', '尺寸', '吉'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 78,
      tags: ['吉'],
    },
    impact: { wealth: 4, career: 3 },
    improvement: '玄关宽度宜与门相当，深度约1.5-2米为佳',
  },
  {
    id: 'entrance-shoe-cabinet-height',
    name: '玄关鞋柜高度',
    category: 'entrance',
    applicableTo: ['entrance'],
    source: ['现代风水', '阳宅三要'],
    heritage: 'both',
    priority: 70,
    weight: 65,
    confidence: 80,
    referenceIds: ['xd-025', 'yzsy-020'],
    tags: ['玄关', '鞋柜', '吉'],
    schools: ['modern', 'bazhai'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 72,
      tags: ['平'],
    },
    impact: { health: 2, wealth: 1 },
    improvement: '鞋柜高度不宜超过成人肩部，宜低于胸口',
  },
  {
    id: 'entrance-mirror-not-facing-door',
    name: '玄关镜子不对门',
    category: 'entrance',
    applicableTo: ['entrance'],
    source: ['现代风水', '阳宅十书'],
    heritage: 'both',
    priority: 78,
    weight: 75,
    confidence: 85,
    referenceIds: ['xd-030', 'yzsx-018'],
    tags: ['玄关', '镜子', '凶'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'inauspicious',
      score: 50,
      tags: ['凶'],
    },
    impact: { wealth: -4, relationship: -2 },
    improvement: '将镜子移至侧面或用布帘遮挡，避免正对大门',
  },
  {
    id: 'entrance-no-clutter',
    name: '玄关杂物（忌堆积）',
    category: 'entrance',
    applicableTo: ['entrance'],
    source: ['黄帝宅经', '现代风水'],
    heritage: 'both',
    priority: 72,
    weight: 68,
    confidence: 82,
    referenceIds: ['hdzj-015', 'xd-035'],
    tags: ['玄关', '杂物', '凶'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'inauspicious',
      score: 55,
      tags: ['凶'],
    },
    impact: { wealth: -3, health: -2, career: -2 },
    improvement: '及时清理杂物，保持玄关通畅明亮',
  },
]
