/**
 * Kitchen Rules - 厨房规则
 * 
 * 涵盖：灶位、灶口朝向、水火关系、冰箱、水槽、厨房中心、压中宫、采光、通风、油烟、动线、收纳
 */

import type { FengShuiRule, FengShuiContext } from '../../types'

export const KITCHEN_RULES: FengShuiRule[] = [
  {
    id: 'kitchen-good-ventilation',
    name: '厨房通风良好',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['阳宅三要', '现代风水'],
    heritage: 'both',
    priority: 80,
    weight: 75,
    confidence: 88,
    referenceIds: ['yzsy-005'],
    tags: ['厨房', '通风', '油烟', '吉'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => {
      const kitchen = ctx.rooms.find(r => r.roomType === 'kitchen')
      return !!(kitchen && kitchen.score > 65)
    },
    result: {
      type: 'auspicious',
      score: 75,
      tags: ['吉'],
    },
    impact: { health: 4, wealth: 2 },
    improvement: '使用大功率抽油烟机',
  },
  {
    id: 'kitchen-water-fire-balance',
    name: '水火既济',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['阳宅三要', '黄帝宅经'],
    heritage: 'classical',
    priority: 85,
    weight: 80,
    confidence: 85,
    referenceIds: ['yzsy-006', 'hzj-009'],
    tags: ['厨房', '水火', '平衡'],
    schools: ['bazhai', 'xuankong'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 70,
      tags: ['平'],
    },
    impact: { health: 3, wealth: 3, relationship: 2 },
    improvement: '灶台与水槽保持适当距离',
  },
  {
    id: 'kitchen-stove-good-direction',
    name: '灶口朝向吉',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['八宅明镜', '阳宅三要'],
    heritage: 'classical',
    priority: 75,
    weight: 70,
    confidence: 80,
    referenceIds: ['bzmj-002', 'yzsy-016'],
    tags: ['厨房', '灶位', '朝向', '吉'],
    schools: ['bazhai'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 70,
      tags: ['平'],
    },
    impact: { wealth: 4, health: 2 },
    improvement: '根据命卦调整灶口朝向',
  },
  {
    id: 'kitchen-not-center',
    name: '厨不压中宫',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['阳宅三要', '阳宅十书'],
    heritage: 'classical',
    priority: 90,
    weight: 85,
    confidence: 85,
    referenceIds: ['yzsy-010', 'yzsx-003'],
    tags: ['厨房', '中宫', '凶'],
    schools: ['bazhai', 'xuankong'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 75,
      tags: ['平'],
    },
    impact: { health: -3, wealth: -2 },
    improvement: '厨房不宜在房屋中心',
  },
  {
    id: 'kitchen-no-door-direct',
    name: '厨房不门对门',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['阳宅三要'],
    heritage: 'classical',
    priority: 80,
    weight: 75,
    confidence: 80,
    referenceIds: ['yzsy-006'],
    tags: ['厨房', '门冲', '凶'],
    schools: ['bazhai'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 70,
      tags: ['平'],
    },
    impact: { wealth: -2, health: -1 },
    improvement: '设置玄关或门帘',
  },
  {
    id: 'kitchen-good-lighting',
    name: '厨房采光充足',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 70,
    weight: 65,
    confidence: 85,
    referenceIds: ['xd-009'],
    tags: ['厨房', '采光', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 75,
      tags: ['吉'],
    },
    impact: { health: 3, wealth: 1 },
    improvement: '增加厨房照明',
  },
  {
    id: 'kitchen-clean-tidy',
    name: '厨房整洁',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 65,
    weight: 60,
    confidence: 80,
    referenceIds: ['xd-010'],
    tags: ['厨房', '整洁', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 70,
      tags: ['吉'],
    },
    impact: { health: 3, wealth: 2 },
    improvement: '保持厨房清洁整齐',
  },
]
