/**
 * Kitchen Rules - 厨房规则
 * 
 * 涵盖：灶位、灶口朝向、水火关系、冰箱、水槽、厨房中心、压中宫、采光、通风、油烟、动线、收纳、开放式厨房
 */

import type { FengShuiRule, FengShuiContext } from '../../types'

export const KITCHEN_RULES: FengShuiRule[] = [
  {
    id: 'kitchen-good-ventilation',
    name: '厨房通风良好',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['阳宅三要', '现代风水'],
    heritage: 'both',
    priority: 80,
    weight: 75,
    confidence: 88,
    referenceIds: ['yzsy-005'],
    tags: ['厨房', '通风', '油烟', '吉'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => {
      const kitchen = ctx.rooms.find(r => r.roomType === 'kitchen')
      return !!(kitchen && kitchen.score > 65)
    },
    result: {
      type: 'auspicious',
      score: 75,
      tags: ['吉'],
    },
    impact: { health: 4, wealth: 2 },
    improvement: '使用大功率抽油烟机',
  },
  {
    id: 'kitchen-water-fire-balance',
    name: '水火既济',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['阳宅三要', '黄帝宅经'],
    heritage: 'classical',
    priority: 85,
    weight: 80,
    confidence: 85,
    referenceIds: ['yzsy-006', 'hzj-009'],
    tags: ['厨房', '水火', '平衡'],
    schools: ['bazhai', 'xuankong'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 70,
      tags: ['平'],
    },
    impact: { health: 3, wealth: 3, relationship: 2 },
    improvement: '灶台与水槽保持适当距离',
  },
  {
    id: 'kitchen-stove-good-direction',
    name: '灶口朝向吉',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['八宅明镜', '阳宅三要'],
    heritage: 'classical',
    priority: 75,
    weight: 70,
    confidence: 80,
    referenceIds: ['bzmj-002', 'yzsy-016'],
    tags: ['厨房', '灶位', '朝向', '吉'],
    schools: ['bazhai'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 70,
      tags: ['平'],
    },
    impact: { wealth: 4, health: 2 },
    improvement: '根据命卦调整灶口朝向',
  },
  {
    id: 'kitchen-not-center',
    name: '厨不压中宫',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['阳宅三要', '阳宅十书'],
    heritage: 'classical',
    priority: 90,
    weight: 85,
    confidence: 85,
    referenceIds: ['yzsy-010', 'yzsx-003'],
    tags: ['厨房', '中宫', '凶'],
    schools: ['bazhai', 'xuankong'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 75,
      tags: ['平'],
    },
    impact: { health: -3, wealth: -2 },
    improvement: '厨房不宜在房屋中心',
  },
  {
    id: 'kitchen-no-door-direct',
    name: '厨房不门对门',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['阳宅三要'],
    heritage: 'classical',
    priority: 80,
    weight: 75,
    confidence: 80,
    referenceIds: ['yzsy-006'],
    tags: ['厨房', '门冲', '凶'],
    schools: ['bazhai'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 70,
      tags: ['平'],
    },
    impact: { wealth: -2, health: -1 },
    improvement: '设置玄关或门帘',
  },
  {
    id: 'kitchen-good-lighting',
    name: '厨房采光充足',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 70,
    weight: 65,
    confidence: 85,
    referenceIds: ['xd-009'],
    tags: ['厨房', '采光', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 75,
      tags: ['吉'],
    },
    impact: { health: 3, wealth: 1 },
    improvement: '增加厨房照明',
  },
  {
    id: 'kitchen-clean-tidy',
    name: '厨房整洁',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 65,
    weight: 60,
    confidence: 80,
    referenceIds: ['xd-010'],
    tags: ['厨房', '整洁', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 70,
      tags: ['吉'],
    },
    impact: { health: 3, wealth: 2 },
    improvement: '保持厨房清洁整齐',
  },
  {
    id: 'kitchen-stove-away-sink',
    name: '灶台不靠水槽',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['阳宅三要', '八宅明镜'],
    heritage: 'classical',
    priority: 88,
    weight: 82,
    confidence: 85,
    referenceIds: ['yzsy-007', 'bzmj-008'],
    tags: ['厨房', '灶台', '水槽', '水火不容', '凶'],
    schools: ['bazhai', 'xuankong'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 65,
      tags: ['平'],
    },
    impact: { health: -4, wealth: -3, relationship: -2 },
    improvement: '灶台与水槽之间至少保持60厘米距离，或用操作台分隔',
  },
  {
    id: 'kitchen-stove-away-fridge',
    name: '灶台不靠冰箱',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['阳宅三要', '现代风水'],
    heritage: 'both',
    priority: 82,
    weight: 78,
    confidence: 82,
    referenceIds: ['yzsy-008', 'xd-011'],
    tags: ['厨房', '灶台', '冰箱', '水火相克', '凶'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 68,
      tags: ['平'],
    },
    impact: { wealth: -4, health: -2 },
    improvement: '冰箱与灶台不宜相邻，至少保持一米以上距离',
  },
  {
    id: 'kitchen-workflow-rational',
    name: '厨房动线合理',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 72,
    weight: 68,
    confidence: 78,
    referenceIds: ['xd-012'],
    tags: ['厨房', '动线', '布局', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => {
      const kitchen = ctx.rooms.find(r => r.roomType === 'kitchen')
      return !!(kitchen && kitchen.score > 60)
    },
    result: {
      type: 'auspicious',
      score: 72,
      tags: ['吉'],
    },
    impact: { health: 3, wealth: 2, relationship: 1 },
    improvement: '遵循冰箱-水槽-灶台的黄金三角动线布局',
  },
  {
    id: 'kitchen-storage-organized',
    name: '厨房收纳整洁',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['现代风水'],
    heritage: 'modern',
    priority: 68,
    weight: 62,
    confidence: 75,
    referenceIds: ['xd-013'],
    tags: ['厨房', '收纳', '整洁', '吉'],
    schools: ['modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'auspicious',
      score: 70,
      tags: ['吉'],
    },
    impact: { health: 3, wealth: 2 },
    improvement: '厨具分类收纳，台面保持清爽无杂物',
  },
  {
    id: 'kitchen-not-open',
    name: '厨房不开放',
    category: 'kitchen',
    applicableTo: ['kitchen'],
    source: ['阳宅三要', '现代风水'],
    heritage: 'both',
    priority: 85,
    weight: 80,
    confidence: 78,
    referenceIds: ['yzsy-009', 'xd-014'],
    tags: ['厨房', '开放式', '油烟', '凶'],
    schools: ['bazhai', 'modern'],
    condition: (ctx: FengShuiContext) => true,
    result: {
      type: 'neutral',
      score: 65,
      tags: ['平'],
    },
    impact: { health: -4, wealth: -2, relationship: -2 },
    improvement: '开放式厨房宜用吧台或玻璃门分隔，加强抽油烟机功率',
  },
]
