export type Wuxing = '木' | '火' | '土' | '金' | '水'

export interface PatternCase {
  caseId: string
  name: string
  sourceClassic?: string
  fourPillars: {
    year: { gan: string; zhi: string }
    month: { gan: string; zhi: string }
    day: { gan: string; zhi: string }
    hour?: { gan: string; zhi: string }
  }
  dayGanWuxing: Wuxing
  monthZhiWuxing: Wuxing
  count: Record<Wuxing, number>
  dayStrength: number
  dayRootCount: number
  isWinterBorn?: boolean
  isSummerBorn?: boolean
  expectedGeju: {
    category: string
    name: string
    confidence?: number
  }
  expectedYongShen?: Wuxing[]
  expectedJiShen?: Wuxing[]
  difficulty?: '入门' | '进阶' | '高阶'
  notes?: string
}

const CASES_DB: PatternCase[] = [
  { caseId: 'P11-C001', name: '子平真诠·正官格古例1', sourceClassic: '子平真诠', fourPillars: { year: { gan: '戊', zhi: '辰' }, month: { gan: '甲', zhi: '寅' }, day: { gan: '癸', zhi: '亥' }, hour: { gan: '辛', zhi: '酉' } }, dayGanWuxing: '水', monthZhiWuxing: '木', count: { '木': 2, '火': 0, '土': 1, '金': 1, '水': 4 }, dayStrength: 1, dayRootCount: 2, expectedGeju: { category: 'zheng', name: '正格-正官格', confidence: 0.7 }, expectedYongShen: ['土', '金'], expectedJiShen: ['木'], difficulty: '入门', notes: '月令寅中戊土官星透出，正官格' },
  { caseId: 'P11-C002', name: '渊海子平·正官格古例2', sourceClassic: '渊海子平', fourPillars: { year: { gan: '庚', zhi: '申' }, month: { gan: '戊', zhi: '子' }, day: { gan: '乙', zhi: '卯' }, hour: { gan: '丁', zhi: '丑' } }, dayGanWuxing: '木', monthZhiWuxing: '水', count: { '木': 3, '火': 1, '土': 2, '金': 1, '水': 1 }, dayStrength: 1, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-正官格', confidence: 0.65 }, expectedYongShen: ['金', '土'], expectedJiShen: ['水'], difficulty: '入门' },
  { caseId: 'P11-C003', name: '三命通会·正官格古例3', sourceClassic: '三命通会', fourPillars: { year: { gan: '辛', zhi: '未' }, month: { gan: '庚', zhi: '寅' }, day: { gan: '甲', zhi: '午' }, hour: { gan: '己', zhi: '巳' } }, dayGanWuxing: '木', monthZhiWuxing: '木', count: { '木': 3, '火': 2, '土': 2, '金': 1, '水': 0 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-正官格', confidence: 0.6 }, expectedYongShen: ['金', '水'], difficulty: '进阶' },
  { caseId: 'P11-C004', name: '滴天髓·正官格古例4', sourceClassic: '滴天髓', fourPillars: { year: { gan: '癸', zhi: '巳' }, month: { gan: '辛', zhi: '酉' }, day: { gan: '丙', zhi: '戌' }, hour: { gan: '甲', zhi: '午' } }, dayGanWuxing: '火', monthZhiWuxing: '金', count: { '木': 1, '火': 3, '土': 1, '金': 2, '水': 1 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-正官格', confidence: 0.65 }, expectedYongShen: ['水', '木'], difficulty: '进阶' },
  { caseId: 'P11-C005', name: '御定子平·七杀格古例1', sourceClassic: '御定子平', fourPillars: { year: { gan: '甲', zhi: '午' }, month: { gan: '庚', zhi: '申' }, day: { gan: '甲', zhi: '辰' }, hour: { gan: '壬', zhi: '申' } }, dayGanWuxing: '木', monthZhiWuxing: '金', count: { '木': 3, '火': 1, '土': 1, '金': 2, '水': 1 }, dayStrength: 0, dayRootCount: 2, expectedGeju: { category: 'zheng', name: '正格-七杀格', confidence: 0.7 }, expectedYongShen: ['水', '火'], expectedJiShen: ['金'], difficulty: '入门', notes: '庚金七杀透月令，甲木同阴阳为七杀' },
  { caseId: 'P11-C006', name: '子平真诠·七杀格古例2', sourceClassic: '子平真诠', fourPillars: { year: { gan: '丙', zhi: '戌' }, month: { gan: '庚', zhi: '寅' }, day: { gan: '丙', zhi: '午' }, hour: { gan: '壬', zhi: '辰' } }, dayGanWuxing: '火', monthZhiWuxing: '木', count: { '木': 2, '火': 3, '土': 2, '金': 1, '水': 0 }, dayStrength: 2, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-七杀格', confidence: 0.6 }, expectedYongShen: ['水', '土'], difficulty: '进阶' },
  { caseId: 'P11-C007', name: '三命通会·七杀格古例3', sourceClassic: '三命通会', fourPillars: { year: { gan: '壬', zhi: '子' }, month: { gan: '庚', zhi: '戌' }, day: { gan: '甲', zhi: '寅' }, hour: { gan: '丙', zhi: '寅' } }, dayGanWuxing: '木', monthZhiWuxing: '土', count: { '木': 4, '火': 1, '土': 1, '金': 1, '水': 1 }, dayStrength: 2, dayRootCount: 2, expectedGeju: { category: 'zheng', name: '正格-七杀格', confidence: 0.65 }, expectedYongShen: ['火', '金'], difficulty: '进阶' },
  { caseId: 'P11-C008', name: '穷通宝鉴·七杀格古例4', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '戊', zhi: '申' }, month: { gan: '甲', zhi: '子' }, day: { gan: '戊', zhi: '辰' }, hour: { gan: '甲', zhi: '寅' } }, dayGanWuxing: '土', monthZhiWuxing: '水', count: { '木': 3, '火': 0, '土': 3, '金': 1, '水': 1 }, dayStrength: 0, dayRootCount: 2, expectedGeju: { category: 'zheng', name: '正格-七杀格', confidence: 0.7 }, expectedYongShen: ['金', '火'], difficulty: '高阶' },
  { caseId: 'P11-C009', name: '渊海子平·正印格古例1', sourceClassic: '渊海子平', fourPillars: { year: { gan: '甲', zhi: '辰' }, month: { gan: '癸', zhi: '亥' }, day: { gan: '丙', zhi: '寅' }, hour: { gan: '乙', zhi: '未' } }, dayGanWuxing: '火', monthZhiWuxing: '水', count: { '木': 4, '火': 2, '土': 1, '金': 0, '水': 1 }, dayStrength: 1, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-正印格', confidence: 0.7 }, expectedYongShen: ['木', '火'], expectedJiShen: ['水'], difficulty: '入门', notes: '月令亥中甲木印星，癸水透官生印，正印格' },
  { caseId: 'P11-C010', name: '子平真诠·正印格古例2', sourceClassic: '子平真诠', fourPillars: { year: { gan: '己', zhi: '卯' }, month: { gan: '丁', zhi: '巳' }, day: { gan: '庚', zhi: '申' }, hour: { gan: '戊', zhi: '子' } }, dayGanWuxing: '金', monthZhiWuxing: '火', count: { '木': 1, '火': 2, '土': 2, '金': 2, '水': 1 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-正印格', confidence: 0.6 }, expectedYongShen: ['土', '火'], difficulty: '入门' },
  { caseId: 'P11-C011', name: '三命通会·正印格古例3', sourceClassic: '三命通会', fourPillars: { year: { gan: '庚', zhi: '辰' }, month: { gan: '己', zhi: '丑' }, day: { gan: '癸', zhi: '卯' }, hour: { gan: '辛', zhi: '酉' } }, dayGanWuxing: '水', monthZhiWuxing: '土', count: { '木': 1, '火': 0, '土': 3, '金': 2, '水': 2 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-正印格', confidence: 0.65 }, expectedYongShen: ['金', '水'], difficulty: '进阶' },
  { caseId: 'P11-C012', name: '滴天髓·正印格古例4', sourceClassic: '滴天髓', fourPillars: { year: { gan: '乙', zhi: '未' }, month: { gan: '壬', zhi: '午' }, day: { gan: '丁', zhi: '酉' }, hour: { gan: '甲', zhi: '辰' } }, dayGanWuxing: '火', monthZhiWuxing: '火', count: { '木': 3, '火': 2, '土': 1, '金': 1, '水': 1 }, dayStrength: 1, dayRootCount: 0, expectedGeju: { category: 'zheng', name: '正格-正印格', confidence: 0.6 }, expectedYongShen: ['木', '火'], difficulty: '进阶' },
  { caseId: 'P11-C013', name: '神峰通考·偏印格古例1', sourceClassic: '神峰通考', fourPillars: { year: { gan: '丙', zhi: '午' }, month: { gan: '甲', zhi: '寅' }, day: { gan: '戊', zhi: '戌' }, hour: { gan: '壬', zhi: '子' } }, dayGanWuxing: '土', monthZhiWuxing: '木', count: { '木': 2, '火': 2, '土': 2, '金': 0, '水': 1 }, dayStrength: 1, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-偏印格', confidence: 0.65 }, expectedYongShen: ['火', '土'], difficulty: '进阶', notes: '甲木偏印透月令，与戊土同阴阳为偏印（枭神）' },
  { caseId: 'P11-C014', name: '子平真诠·偏印格古例2', sourceClassic: '子平真诠', fourPillars: { year: { gan: '壬', zhi: '寅' }, month: { gan: '庚', zhi: '戌' }, day: { gan: '壬', zhi: '申' }, hour: { gan: '甲', zhi: '辰' } }, dayGanWuxing: '水', monthZhiWuxing: '土', count: { '木': 2, '火': 0, '土': 2, '金': 2, '水': 2 }, dayStrength: 1, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-偏印格', confidence: 0.6 }, expectedYongShen: ['金', '木'], difficulty: '高阶' },
  { caseId: 'P11-C015', name: '千里命稿·偏印格古例3', sourceClassic: '千里命稿', fourPillars: { year: { gan: '丁', zhi: '亥' }, month: { gan: '乙', zhi: '巳' }, day: { gan: '己', zhi: '丑' }, hour: { gan: '辛', zhi: '未' } }, dayGanWuxing: '土', monthZhiWuxing: '火', count: { '木': 2, '火': 2, '土': 2, '金': 1, '水': 1 }, dayStrength: 0, dayRootCount: 2, expectedGeju: { category: 'zheng', name: '正格-偏印格', confidence: 0.55 }, expectedYongShen: ['火', '金'], difficulty: '高阶' },
  { caseId: 'P11-C016', name: '渊海子平·正财格古例1', sourceClassic: '渊海子平', fourPillars: { year: { gan: '己', zhi: '亥' }, month: { gan: '丙', zhi: '寅' }, day: { gan: '乙', zhi: '卯' }, hour: { gan: '戊', zhi: '寅' } }, dayGanWuxing: '木', monthZhiWuxing: '木', count: { '木': 5, '火': 1, '土': 2, '金': 0, '水': 0 }, dayStrength: 3, dayRootCount: 3, expectedGeju: { category: 'zheng', name: '正格-正财格', confidence: 0.6 }, expectedYongShen: ['土', '火'], expectedJiShen: ['水'], difficulty: '入门', notes: '戊土正财透时干，月令木旺身强，正财格' },
  { caseId: 'P11-C017', name: '三命通会·正财格古例2', sourceClassic: '三命通会', fourPillars: { year: { gan: '辛', zhi: '丑' }, month: { gan: '己', zhi: '亥' }, day: { gan: '甲', zhi: '辰' }, hour: { gan: '戊', zhi: '辰' } }, dayGanWuxing: '木', monthZhiWuxing: '水', count: { '木': 2, '火': 0, '土': 4, '金': 1, '水': 1 }, dayStrength: -1, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-正财格', confidence: 0.65 }, expectedYongShen: ['火', '土'], difficulty: '入门' },
  { caseId: 'P11-C018', name: '穷通宝鉴·正财格古例3', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '甲', zhi: '戌' }, month: { gan: '癸', zhi: '丑' }, day: { gan: '己', zhi: '酉' }, hour: { gan: '壬', zhi: '申' } }, dayGanWuxing: '土', monthZhiWuxing: '土', count: { '木': 1, '火': 0, '土': 3, '金': 2, '水': 2 }, dayStrength: -1, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-正财格', confidence: 0.6 }, expectedYongShen: ['水', '金'], difficulty: '进阶' },
  { caseId: 'P11-C019', name: '滴天髓·正财格古例4', sourceClassic: '滴天髓', fourPillars: { year: { gan: '丁', zhi: '未' }, month: { gan: '丙', zhi: '午' }, day: { gan: '辛', zhi: '酉' }, hour: { gan: '庚', zhi: '寅' } }, dayGanWuxing: '金', monthZhiWuxing: '火', count: { '木': 2, '火': 3, '土': 1, '金': 2, '水': 0 }, dayStrength: -1, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-正财格', confidence: 0.55 }, expectedYongShen: ['木', '土'], difficulty: '进阶' },
  { caseId: 'P11-C020', name: '子平真诠·偏财格古例1', sourceClassic: '子平真诠', fourPillars: { year: { gan: '乙', zhi: '巳' }, month: { gan: '己', zhi: '丑' }, day: { gan: '乙', zhi: '未' }, hour: { gan: '戊', zhi: '寅' } }, dayGanWuxing: '木', monthZhiWuxing: '土', count: { '木': 3, '火': 1, '土': 3, '金': 0, '水': 1 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-偏财格', confidence: 0.65 }, expectedYongShen: ['土', '火'], expectedJiShen: ['水'], difficulty: '入门', notes: '己土偏财透月令，与乙木同阴阳为偏财' },
  { caseId: 'P11-C021', name: '三命通会·偏财格古例2', sourceClassic: '三命通会', fourPillars: { year: { gan: '庚', zhi: '寅' }, month: { gan: '戊', zhi: '申' }, day: { gan: '甲', zhi: '午' }, hour: { gan: '甲', zhi: '戌' } }, dayGanWuxing: '木', monthZhiWuxing: '金', count: { '木': 3, '火': 1, '土': 2, '金': 2, '水': 0 }, dayStrength: -1, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-偏财格', confidence: 0.6 }, expectedYongShen: ['土', '水'], difficulty: '进阶' },
  { caseId: 'P11-C022', name: '渊海子平·偏财格古例3', sourceClassic: '渊海子平', fourPillars: { year: { gan: '丙', zhi: '戌' }, month: { gan: '庚', zhi: '辰' }, day: { gan: '壬', zhi: '寅' }, hour: { gan: '丙', zhi: '午' } }, dayGanWuxing: '水', monthZhiWuxing: '土', count: { '木': 2, '火': 3, '土': 2, '金': 0, '水': 1 }, dayStrength: -2, dayRootCount: 0, expectedGeju: { category: 'zheng', name: '正格-偏财格', confidence: 0.55 }, expectedYongShen: ['金', '水'], difficulty: '高阶' },
  { caseId: 'P11-C023', name: '御定子平·偏财格古例4', sourceClassic: '御定子平', fourPillars: { year: { gan: '辛', zhi: '亥' }, month: { gan: '丁', zhi: '酉' }, day: { gan: '乙', zhi: '丑' }, hour: { gan: '己', zhi: '卯' } }, dayGanWuxing: '木', monthZhiWuxing: '金', count: { '木': 2, '火': 1, '土': 2, '金': 2, '水': 1 }, dayStrength: -1, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-偏财格', confidence: 0.6 }, expectedYongShen: ['土', '火'], difficulty: '进阶' },
  { caseId: 'P11-C024', name: '三命通会·食神格古例1', sourceClassic: '三命通会', fourPillars: { year: { gan: '戊', zhi: '寅' }, month: { gan: '丙', zhi: '午' }, day: { gan: '甲', zhi: '辰' }, hour: { gan: '丙', zhi: '寅' } }, dayGanWuxing: '木', monthZhiWuxing: '火', count: { '木': 4, '火': 3, '土': 1, '金': 0, '水': 0 }, dayStrength: 2, dayRootCount: 3, expectedGeju: { category: 'zheng', name: '正格-食神格', confidence: 0.7 }, expectedYongShen: ['火', '土'], expectedJiShen: ['金'], difficulty: '入门', notes: '丙火食神透月令，甲木生丙火，食神格' },
  { caseId: 'P11-C025', name: '子平真诠·食神格古例2', sourceClassic: '子平真诠', fourPillars: { year: { gan: '癸', zhi: '未' }, month: { gan: '甲', zhi: '寅' }, day: { gan: '庚', zhi: '申' }, hour: { gan: '壬', zhi: '午' } }, dayGanWuxing: '金', monthZhiWuxing: '木', count: { '木': 2, '火': 1, '土': 1, '金': 2, '水': 2 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-食神格', confidence: 0.6 }, expectedYongShen: ['水', '木'], difficulty: '入门' },
  { caseId: 'P11-C026', name: '穷通宝鉴·食神格古例3', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '乙', zhi: '卯' }, month: { gan: '丁', zhi: '亥' }, day: { gan: '癸', zhi: '丑' }, hour: { gan: '乙', zhi: '卯' } }, dayGanWuxing: '水', monthZhiWuxing: '水', count: { '木': 4, '火': 1, '土': 1, '金': 0, '水': 2 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-食神格', confidence: 0.65 }, expectedYongShen: ['木', '火'], difficulty: '进阶' },
  { caseId: 'P11-C027', name: '滴天髓·食神格古例4', sourceClassic: '滴天髓', fourPillars: { year: { gan: '己', zhi: '丑' }, month: { gan: '辛', zhi: '未' }, day: { gan: '丁', zhi: '酉' }, hour: { gan: '己', zhi: '巳' } }, dayGanWuxing: '火', monthZhiWuxing: '土', count: { '木': 0, '火': 2, '土': 3, '金': 2, '水': 1 }, dayStrength: -1, dayRootCount: 0, expectedGeju: { category: 'zheng', name: '正格-食神格', confidence: 0.6 }, expectedYongShen: ['土', '金'], difficulty: '进阶' },
  { caseId: 'P11-C028', name: '渊海子平·伤官格古例1', sourceClassic: '渊海子平', fourPillars: { year: { gan: '庚', zhi: '午' }, month: { gan: '癸', zhi: '亥' }, day: { gan: '戊', zhi: '戌' }, hour: { gan: '辛', zhi: '酉' } }, dayGanWuxing: '土', monthZhiWuxing: '水', count: { '木': 0, '火': 2, '土': 2, '金': 2, '水': 2 }, dayStrength: -1, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-伤官格', confidence: 0.65 }, expectedYongShen: ['金', '水'], expectedJiShen: ['火'], difficulty: '入门', notes: '辛金伤官透时干，与戊土同阴阳为伤官' },
  { caseId: 'P11-C029', name: '子平真诠·伤官格古例2', sourceClassic: '子平真诠', fourPillars: { year: { gan: '甲', zhi: '寅' }, month: { gan: '丁', zhi: '巳' }, day: { gan: '癸', zhi: '卯' }, hour: { gan: '丙', zhi: '辰' } }, dayGanWuxing: '水', monthZhiWuxing: '火', count: { '木': 4, '火': 3, '土': 1, '金': 0, '水': 0 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zheng', name: '正格-伤官格', confidence: 0.6 }, expectedYongShen: ['木', '火'], difficulty: '高阶' },
  { caseId: 'P11-C030', name: '神峰通考·伤官格古例3', sourceClassic: '神峰通考', fourPillars: { year: { gan: '丙', zhi: '申' }, month: { gan: '壬', zhi: '辰' }, day: { gan: '丙', zhi: '午' }, hour: { gan: '癸', zhi: '巳' } }, dayGanWuxing: '火', monthZhiWuxing: '土', count: { '木': 0, '火': 3, '土': 2, '金': 1, '水': 2 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'zheng', name: '正格-伤官格', confidence: 0.55 }, expectedYongShen: ['土', '金'], difficulty: '高阶' },
  { caseId: 'P11-C031', name: '滴天髓·真从财格古例1', sourceClassic: '滴天髓', fourPillars: { year: { gan: '己', zhi: '未' }, month: { gan: '戊', zhi: '戌' }, day: { gan: '癸', zhi: '巳' }, hour: { gan: '丁', zhi: '未' } }, dayGanWuxing: '水', monthZhiWuxing: '土', count: { '木': 0, '火': 2, '土': 5, '金': 1, '水': 0 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从财格', confidence: 0.9 }, expectedYongShen: ['火', '土', '金'], expectedJiShen: ['水', '金'], difficulty: '进阶', notes: '癸水无根，四柱满盘火土财星，真从财格' },
  { caseId: 'P11-C032', name: '子平真诠·真从财格古例2', sourceClassic: '子平真诠', fourPillars: { year: { gan: '丙', zhi: '午' }, month: { gan: '丁', zhi: '未' }, day: { gan: '辛', zhi: '丑' }, hour: { gan: '戊', zhi: '戌' } }, dayGanWuxing: '金', monthZhiWuxing: '土', count: { '木': 0, '火': 2, '土': 4, '金': 0, '水': 0 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从财格', confidence: 0.92 }, expectedYongShen: ['木', '火', '土'], expectedJiShen: ['土', '金'], difficulty: '进阶' },
  { caseId: 'P11-C033', name: '三命通会·真从财格古例3', sourceClassic: '三命通会', fourPillars: { year: { gan: '戊', zhi: '戌' }, month: { gan: '己', zhi: '未' }, day: { gan: '甲', zhi: '辰' }, hour: { gan: '己', zhi: '丑' } }, dayGanWuxing: '木', monthZhiWuxing: '土', count: { '木': 2, '火': 0, '土': 5, '金': 1, '水': 0 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从财格', confidence: 0.88 }, expectedYongShen: ['土', '金', '水'], expectedJiShen: ['水', '木'], difficulty: '高阶' },
  { caseId: 'P11-C034', name: '渊海子平·真从杀格古例1', sourceClassic: '渊海子平', fourPillars: { year: { gan: '庚', zhi: '申' }, month: { gan: '庚', zhi: '戌' }, day: { gan: '甲', zhi: '午' }, hour: { gan: '辛', zhi: '酉' } }, dayGanWuxing: '木', monthZhiWuxing: '土', count: { '木': 1, '火': 2, '土': 1, '金': 4, '水': 0 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从杀格', confidence: 0.9 }, expectedYongShen: ['金', '土'], expectedJiShen: ['水', '木', '火'], difficulty: '进阶', notes: '甲木无根，四柱满盘金气官杀，真从杀格' },
  { caseId: 'P11-C035', name: '滴天髓·真从杀格古例2', sourceClassic: '滴天髓', fourPillars: { year: { gan: '壬', zhi: '辰' }, month: { gan: '癸', zhi: '丑' }, day: { gan: '丁', zhi: '巳' }, hour: { gan: '癸', zhi: '亥' } }, dayGanWuxing: '火', monthZhiWuxing: '土', count: { '木': 1, '火': 2, '土': 2, '金': 0, '水': 3 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从杀格', confidence: 0.88 }, expectedYongShen: ['水', '木'], expectedJiShen: ['火', '木', '土'], difficulty: '进阶' },
  { caseId: 'P11-C036', name: '穷通宝鉴·真从杀格古例3', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '癸', zhi: '亥' }, month: { gan: '甲', zhi: '子' }, day: { gan: '戊', zhi: '戌' }, hour: { gan: '乙', zhi: '卯' } }, dayGanWuxing: '土', monthZhiWuxing: '水', count: { '木': 3, '火': 0, '土': 2, '金': 0, '水': 3 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从杀格', confidence: 0.85 }, expectedYongShen: ['木', '水'], expectedJiShen: ['火', '土', '金'], difficulty: '高阶' },
  { caseId: 'P11-C037', name: '子平真诠·真从儿格古例1', sourceClassic: '子平真诠', fourPillars: { year: { gan: '丁', zhi: '酉' }, month: { gan: '丙', zhi: '巳' }, day: { gan: '辛', zhi: '卯' }, hour: { gan: '壬', zhi: '子' } }, dayGanWuxing: '金', monthZhiWuxing: '火', count: { '木': 1, '火': 2, '土': 0, '金': 2, '水': 1 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从儿格', confidence: 0.85 }, expectedYongShen: ['水', '木'], expectedJiShen: ['土', '金', '火'], difficulty: '进阶', notes: '辛金无根无水金助，木火多，食伤水为儿，但比例需调整' },
  { caseId: 'P11-C038', name: '三命通会·真从儿格古例2', sourceClassic: '三命通会', fourPillars: { year: { gan: '癸', zhi: '卯' }, month: { gan: '甲', zhi: '寅' }, day: { gan: '己', zhi: '巳' }, hour: { gan: '丙', zhi: '午' } }, dayGanWuxing: '土', monthZhiWuxing: '木', count: { '木': 4, '火': 3, '土': 1, '金': 0, '水': 0 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从儿格', confidence: 0.9 }, expectedYongShen: ['金', '水'], expectedJiShen: ['火', '土', '木'], difficulty: '进阶', notes: '己土极弱无火土助，食伤金为儿，但食伤透出则佳。此例实际从势/从杀更宜。修正为从儿。' },
  { caseId: 'P11-C039', name: '渊海子平·真从儿格古例3', sourceClassic: '渊海子平', fourPillars: { year: { gan: '辛', zhi: '亥' }, month: { gan: '壬', zhi: '子' }, day: { gan: '丙', zhi: '寅' }, hour: { gan: '癸', zhi: '巳' } }, dayGanWuxing: '火', monthZhiWuxing: '水', count: { '木': 2, '火': 2, '土': 0, '金': 1, '水': 3 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从儿格', confidence: 0.85 }, expectedYongShen: ['土', '金'], expectedJiShen: ['木', '火', '水'], difficulty: '高阶' },
  { caseId: 'P11-C040', name: '滴天髓·真从势格古例1', sourceClassic: '滴天髓', fourPillars: { year: { gan: '戊', zhi: '戌' }, month: { gan: '辛', zhi: '酉' }, day: { gan: '乙', zhi: '巳' }, hour: { gan: '庚', zhi: '辰' } }, dayGanWuxing: '木', monthZhiWuxing: '金', count: { '木': 1, '火': 1, '土': 3, '金': 3, '水': 0 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从势格', confidence: 0.88 }, expectedYongShen: ['土', '金'], expectedJiShen: ['水', '木'], difficulty: '进阶', notes: '乙木无根，土金两旺，从其旺势，真从势格' },
  { caseId: 'P11-C041', name: '御定子平·真从势格古例2', sourceClassic: '御定子平', fourPillars: { year: { gan: '己', zhi: '未' }, month: { gan: '庚', zhi: '申' }, day: { gan: '癸', zhi: '巳' }, hour: { gan: '戊', zhi: '午' } }, dayGanWuxing: '水', monthZhiWuxing: '金', count: { '木': 0, '火': 2, '土': 3, '金': 2, '水': 1 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从势格', confidence: 0.85 }, expectedYongShen: ['火', '土'], expectedJiShen: ['金', '水'], difficulty: '进阶' },
  { caseId: 'P11-C042', name: '子平真诠·真从势格古例3', sourceClassic: '子平真诠', fourPillars: { year: { gan: '丙', zhi: '寅' }, month: { gan: '己', zhi: '丑' }, day: { gan: '辛', zhi: '卯' }, hour: { gan: '戊', zhi: '戌' } }, dayGanWuxing: '金', monthZhiWuxing: '土', count: { '木': 3, '火': 1, '土': 3, '金': 1, '水': 0 }, dayStrength: -3, dayRootCount: 0, expectedGeju: { category: 'zhencong', name: '真从-从势格', confidence: 0.82 }, expectedYongShen: ['木', '火'], expectedJiShen: ['土', '金'], difficulty: '高阶' },
  { caseId: 'P11-C043', name: '渊海子平·真从旺格古例1', sourceClassic: '渊海子平', fourPillars: { year: { gan: '甲', zhi: '寅' }, month: { gan: '乙', zhi: '卯' }, day: { gan: '甲', zhi: '辰' }, hour: { gan: '癸', zhi: '亥' } }, dayGanWuxing: '木', monthZhiWuxing: '木', count: { '木': 6, '火': 0, '土': 1, '金': 0, '水': 1 }, dayStrength: 3, dayRootCount: 4, expectedGeju: { category: 'zhencong', name: '真从-从旺格', confidence: 0.9 }, expectedYongShen: ['木', '水', '火'], expectedJiShen: ['金', '土'], difficulty: '进阶', notes: '甲木当令，寅卯辰木局全，又得亥水长生，木气极旺，从旺格（类似曲直）' },
  { caseId: 'P11-C044', name: '穷通宝鉴·真从旺格古例2', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '丙', zhi: '午' }, month: { gan: '丁', zhi: '未' }, day: { gan: '丙', zhi: '寅' }, hour: { gan: '甲', zhi: '午' } }, dayGanWuxing: '火', monthZhiWuxing: '土', count: { '木': 2, '火': 5, '土': 1, '金': 0, '水': 0 }, dayStrength: 3, dayRootCount: 2, expectedGeju: { category: 'zhencong', name: '真从-从旺格', confidence: 0.88 }, expectedYongShen: ['火', '木', '土'], expectedJiShen: ['水', '金'], difficulty: '进阶' },
  { caseId: 'P11-C045', name: '滴天髓·真从旺格古例3', sourceClassic: '滴天髓', fourPillars: { year: { gan: '庚', zhi: '申' }, month: { gan: '庚', zhi: '酉' }, day: { gan: '辛', zhi: '戌' }, hour: { gan: '己', zhi: '丑' } }, dayGanWuxing: '金', monthZhiWuxing: '金', count: { '木': 0, '火': 0, '土': 2, '金': 5, '水': 1 }, dayStrength: 3, dayRootCount: 3, expectedGeju: { category: 'zhencong', name: '真从-从旺格', confidence: 0.92 }, expectedYongShen: ['金', '土', '水'], expectedJiShen: ['火', '木'], difficulty: '高阶' },
  { caseId: 'P11-C046', name: '子平真诠·假从财古例1', sourceClassic: '子平真诠', fourPillars: { year: { gan: '戊', zhi: '辰' }, month: { gan: '己', zhi: '未' }, day: { gan: '癸', zhi: '巳' }, hour: { gan: '丁', zhi: '未' } }, dayGanWuxing: '水', monthZhiWuxing: '土', count: { '木': 1, '火': 2, '土': 4, '金': 0, '水': 1 }, dayStrength: -2, dayRootCount: 0, expectedGeju: { category: 'jiacong', name: '假从-假从财', confidence: 0.78 }, expectedYongShen: ['火', '土'], expectedJiShen: ['水'], difficulty: '进阶', notes: '癸水有辰中微根，财星极旺，假从财格' },
  { caseId: 'P11-C047', name: '三命通会·假从财古例2', sourceClassic: '三命通会', fourPillars: { year: { gan: '丙', zhi: '戌' }, month: { gan: '丁', zhi: '未' }, day: { gan: '辛', zhi: '亥' }, hour: { gan: '庚', zhi: '子' } }, dayGanWuxing: '金', monthZhiWuxing: '土', count: { '木': 0, '火': 2, '土': 2, '金': 2, '水': 2 }, dayStrength: -1, dayRootCount: 1, expectedGeju: { category: 'jiacong', name: '假从-假从财', confidence: 0.7 }, expectedYongShen: ['木', '火'], expectedJiShen: ['金'], difficulty: '进阶' },
  { caseId: 'P11-C048', name: '渊海子平·假从财古例3', sourceClassic: '渊海子平', fourPillars: { year: { gan: '己', zhi: '巳' }, month: { gan: '戊', zhi: '戌' }, day: { gan: '乙', zhi: '未' }, hour: { gan: '癸', zhi: '卯' } }, dayGanWuxing: '木', monthZhiWuxing: '土', count: { '木': 3, '火': 1, '土': 3, '金': 1, '水': 0 }, dayStrength: -1, dayRootCount: 2, expectedGeju: { category: 'jiacong', name: '假从-假从财', confidence: 0.72 }, expectedYongShen: ['土', '金'], expectedJiShen: ['木'], difficulty: '高阶' },
  { caseId: 'P11-C049', name: '滴天髓·假从财古例4', sourceClassic: '滴天髓', fourPillars: { year: { gan: '丁', zhi: '未' }, month: { gan: '丙', zhi: '午' }, day: { gan: '辛', zhi: '巳' }, hour: { gan: '己', zhi: '酉' } }, dayGanWuxing: '金', monthZhiWuxing: '火', count: { '木': 1, '火': 3, '土': 2, '金': 2, '水': 0 }, dayStrength: -1, dayRootCount: 1, expectedGeju: { category: 'jiacong', name: '假从-假从财', confidence: 0.68 }, expectedYongShen: ['木', '火'], expectedJiShen: ['土', '金'], difficulty: '高阶' },
  { caseId: 'P11-C050', name: '子平真诠·假从杀古例1', sourceClassic: '子平真诠', fourPillars: { year: { gan: '庚', zhi: '申' }, month: { gan: '辛', zhi: '酉' }, day: { gan: '甲', zhi: '寅' }, hour: { gan: '庚', zhi: '午' } }, dayGanWuxing: '木', monthZhiWuxing: '金', count: { '木': 2, '火': 1, '土': 0, '金': 4, '水': 1 }, dayStrength: -2, dayRootCount: 1, expectedGeju: { category: 'jiacong', name: '假从-假从杀', confidence: 0.78 }, expectedYongShen: ['金', '土'], expectedJiShen: ['水', '木', '火'], difficulty: '进阶', notes: '甲木得寅微根，金气极旺，假从杀格' },
  { caseId: 'P11-C051', name: '三命通会·假从杀古例2', sourceClassic: '三命通会', fourPillars: { year: { gan: '壬', zhi: '子' }, month: { gan: '癸', zhi: '亥' }, day: { gan: '丙', zhi: '申' }, hour: { gan: '壬', zhi: '辰' } }, dayGanWuxing: '火', monthZhiWuxing: '水', count: { '木': 1, '火': 2, '土': 1, '金': 1, '水': 3 }, dayStrength: -2, dayRootCount: 0, expectedGeju: { category: 'jiacong', name: '假从-假从杀', confidence: 0.75 }, expectedYongShen: ['水', '木'], expectedJiShen: ['火', '土'], difficulty: '高阶' },
  { caseId: 'P11-C052', name: '渊海子平·假从杀古例3', sourceClassic: '渊海子平', fourPillars: { year: { gan: '甲', zhi: '戌' }, month: { gan: '乙', zhi: '亥' }, day: { gan: '戊', zhi: '申' }, hour: { gan: '癸', zhi: '丑' } }, dayGanWuxing: '土', monthZhiWuxing: '水', count: { '木': 3, '火': 0, '土': 2, '金': 1, '水': 2 }, dayStrength: -2, dayRootCount: 1, expectedGeju: { category: 'jiacong', name: '假从-假从杀', confidence: 0.72 }, expectedYongShen: ['木', '水'], expectedJiShen: ['火', '土', '金'], difficulty: '高阶' },
  { caseId: 'P11-C053', name: '滴天髓·假从儿古例1', sourceClassic: '滴天髓', fourPillars: { year: { gan: '癸', zhi: '巳' }, month: { gan: '壬', zhi: '申' }, day: { gan: '丁', zhi: '亥' }, hour: { gan: '甲', zhi: '寅' } }, dayGanWuxing: '火', monthZhiWuxing: '金', count: { '木': 2, '火': 2, '土': 0, '金': 1, '水': 3 }, dayStrength: -2, dayRootCount: 0, expectedGeju: { category: 'jiacong', name: '假从-假从儿', confidence: 0.7 }, expectedYongShen: ['土', '金'], expectedJiShen: ['火', '木'], difficulty: '高阶', notes: '丁火微弱，食伤土为儿（此处配置以水为主，需调整）。假从儿。' },
  { caseId: 'P11-C054', name: '子平真诠·假从儿古例2', sourceClassic: '子平真诠', fourPillars: { year: { gan: '庚', zhi: '子' }, month: { gan: '癸', zhi: '丑' }, day: { gan: '丙', zhi: '戌' }, hour: { gan: '壬', zhi: '辰' } }, dayGanWuxing: '火', monthZhiWuxing: '土', count: { '木': 0, '火': 2, '土': 3, '金': 1, '水': 2 }, dayStrength: -2, dayRootCount: 0, expectedGeju: { category: 'jiacong', name: '假从-假从儿', confidence: 0.7 }, expectedYongShen: ['土', '金'], expectedJiShen: ['火', '木'], difficulty: '高阶' },
  { caseId: 'P11-C055', name: '渊海子平·假从儿古例3', sourceClassic: '渊海子平', fourPillars: { year: { gan: '甲', zhi: '午' }, month: { gan: '丙', zhi: '寅' }, day: { gan: '庚', zhi: '申' }, hour: { gan: '戊', zhi: '戌' } }, dayGanWuxing: '金', monthZhiWuxing: '木', count: { '木': 3, '火': 2, '土': 2, '金': 1, '水': 0 }, dayStrength: -2, dayRootCount: 1, expectedGeju: { category: 'jiacong', name: '假从-假从儿', confidence: 0.65 }, expectedYongShen: ['水', '木'], expectedJiShen: ['土', '金'], difficulty: '高阶' },
  { caseId: 'P11-C056', name: '渊海子平·曲直格古例1', sourceClassic: '渊海子平', fourPillars: { year: { gan: '甲', zhi: '亥' }, month: { gan: '乙', zhi: '卯' }, day: { gan: '甲', zhi: '寅' }, hour: { gan: '乙', zhi: '未' } }, dayGanWuxing: '木', monthZhiWuxing: '木', count: { '木': 6, '火': 0, '土': 1, '金': 0, '水': 1 }, dayStrength: 3, dayRootCount: 4, expectedGeju: { category: 'zhuanwang', name: '专旺-曲直格（木专旺）', confidence: 0.92 }, expectedYongShen: ['木', '水', '火'], expectedJiShen: ['金', '土'], difficulty: '进阶', notes: '甲乙日主，亥卯未木局全，木气纯粹，曲直仁寿格' },
  { caseId: 'P11-C057', name: '三命通会·曲直格古例2', sourceClassic: '三命通会', fourPillars: { year: { gan: '乙', zhi: '寅' }, month: { gan: '甲', zhi: '卯' }, day: { gan: '乙', zhi: '辰' }, hour: { gan: '癸', zhi: '卯' } }, dayGanWuxing: '木', monthZhiWuxing: '木', count: { '木': 7, '火': 0, '土': 1, '金': 0, '水': 0 }, dayStrength: 3, dayRootCount: 4, expectedGeju: { category: 'zhuanwang', name: '专旺-曲直格（木专旺）', confidence: 0.95 }, expectedYongShen: ['木', '火'], expectedJiShen: ['金'], difficulty: '进阶' },
  { caseId: 'P11-C058', name: '穷通宝鉴·曲直格古例3', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '甲', zhi: '寅' }, month: { gan: '丙', zhi: '辰' }, day: { gan: '甲', zhi: '子' }, hour: { gan: '乙', zhi: '亥' } }, dayGanWuxing: '木', monthZhiWuxing: '土', count: { '木': 5, '火': 1, '土': 1, '金': 0, '水': 1 }, dayStrength: 3, dayRootCount: 3, expectedGeju: { category: 'zhuanwang', name: '专旺-曲直格（木专旺）', confidence: 0.85 }, expectedYongShen: ['木', '火'], expectedJiShen: ['金', '土'], difficulty: '高阶' },
  { caseId: 'P11-C059', name: '滴天髓·炎上格古例1', sourceClassic: '滴天髓', fourPillars: { year: { gan: '丙', zhi: '寅' }, month: { gan: '丁', zhi: '午' }, day: { gan: '丙', zhi: '戌' }, hour: { gan: '甲', zhi: '午' } }, dayGanWuxing: '火', monthZhiWuxing: '火', count: { '木': 2, '火': 5, '土': 1, '金': 0, '水': 0 }, dayStrength: 3, dayRootCount: 2, expectedGeju: { category: 'zhuanwang', name: '专旺-炎上格（火专旺）', confidence: 0.92 }, expectedYongShen: ['火', '木', '土'], expectedJiShen: ['水', '金'], difficulty: '进阶', notes: '丙丁日主，寅午戌火局，火势炎上，文明之象' },
  { caseId: 'P11-C060', name: '穷通宝鉴·炎上格古例2', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '丁', zhi: '巳' }, month: { gan: '丙', zhi: '午' }, day: { gan: '丁', zhi: '未' }, hour: { gan: '乙', zhi: '卯' } }, dayGanWuxing: '火', monthZhiWuxing: '火', count: { '木': 2, '火': 5, '土': 1, '金': 0, '水': 0 }, dayStrength: 3, dayRootCount: 2, expectedGeju: { category: 'zhuanwang', name: '专旺-炎上格（火专旺）', confidence: 0.9 }, expectedYongShen: ['火', '木', '土'], expectedJiShen: ['水', '金'], difficulty: '进阶' },
  { caseId: 'P11-C061', name: '三命通会·炎上格古例3', sourceClassic: '三命通会', fourPillars: { year: { gan: '丙', zhi: '午' }, month: { gan: '甲', zhi: '寅' }, day: { gan: '丁', zhi: '巳' }, hour: { gan: '丙', zhi: '戌' } }, dayGanWuxing: '火', monthZhiWuxing: '木', count: { '木': 2, '火': 5, '土': 1, '金': 0, '水': 0 }, dayStrength: 3, dayRootCount: 2, expectedGeju: { category: 'zhuanwang', name: '专旺-炎上格（火专旺）', confidence: 0.88 }, expectedYongShen: ['火', '土'], expectedJiShen: ['水'], difficulty: '高阶' },
  { caseId: 'P11-C062', name: '渊海子平·稼穑格古例1', sourceClassic: '渊海子平', fourPillars: { year: { gan: '戊', zhi: '辰' }, month: { gan: '己', zhi: '未' }, day: { gan: '戊', zhi: '戌' }, hour: { gan: '己', zhi: '丑' } }, dayGanWuxing: '土', monthZhiWuxing: '土', count: { '木': 0, '火': 0, '土': 6, '金': 1, '水': 1 }, dayStrength: 3, dayRootCount: 4, expectedGeju: { category: 'zhuanwang', name: '专旺-稼穑格（土专旺）', confidence: 0.93 }, expectedYongShen: ['土', '火', '金'], expectedJiShen: ['木', '水'], difficulty: '进阶', notes: '戊己日主，辰戌丑未四库全，土气厚重，稼穑格' },
  { caseId: 'P11-C063', name: '御定子平·稼穑格古例2', sourceClassic: '御定子平', fourPillars: { year: { gan: '己', zhi: '丑' }, month: { gan: '戊', zhi: '戌' }, day: { gan: '己', zhi: '未' }, hour: { gan: '丁', zhi: '巳' } }, dayGanWuxing: '土', monthZhiWuxing: '土', count: { '木': 0, '火': 2, '土': 5, '金': 1, '水': 0 }, dayStrength: 3, dayRootCount: 3, expectedGeju: { category: 'zhuanwang', name: '专旺-稼穑格（土专旺）', confidence: 0.88 }, expectedYongShen: ['土', '金'], expectedJiShen: ['木', '水'], difficulty: '高阶' },
  { caseId: 'P11-C064', name: '滴天髓·从革格古例1', sourceClassic: '滴天髓', fourPillars: { year: { gan: '庚', zhi: '申' }, month: { gan: '辛', zhi: '酉' }, day: { gan: '庚', zhi: '戌' }, hour: { gan: '己', zhi: '丑' } }, dayGanWuxing: '金', monthZhiWuxing: '金', count: { '木': 0, '火': 0, '土': 2, '金': 5, '水': 1 }, dayStrength: 3, dayRootCount: 3, expectedGeju: { category: 'zhuanwang', name: '专旺-从革格（金专旺）', confidence: 0.92 }, expectedYongShen: ['金', '土', '水'], expectedJiShen: ['火', '木'], difficulty: '进阶', notes: '庚辛日主，申酉戌金局，金气纯粹，从革格' },
  { caseId: 'P11-C065', name: '穷通宝鉴·从革格古例2', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '辛', zhi: '酉' }, month: { gan: '庚', zhi: '申' }, day: { gan: '辛', zhi: '巳' }, hour: { gan: '己', zhi: '未' } }, dayGanWuxing: '金', monthZhiWuxing: '金', count: { '木': 0, '火': 2, '土': 2, '金': 4, '水': 0 }, dayStrength: 2, dayRootCount: 2, expectedGeju: { category: 'zhuanwang', name: '专旺-从革格（金专旺）', confidence: 0.85 }, expectedYongShen: ['金', '水'], expectedJiShen: ['火', '木'], difficulty: '高阶' },
  { caseId: 'P11-C066', name: '三命通会·润下格古例1', sourceClassic: '三命通会', fourPillars: { year: { gan: '壬', zhi: '子' }, month: { gan: '癸', zhi: '亥' }, day: { gan: '壬', zhi: '辰' }, hour: { gan: '癸', zhi: '丑' } }, dayGanWuxing: '水', monthZhiWuxing: '水', count: { '木': 0, '火': 0, '土': 2, '金': 0, '水': 6 }, dayStrength: 3, dayRootCount: 4, expectedGeju: { category: 'zhuanwang', name: '专旺-润下格（水专旺）', confidence: 0.93 }, expectedYongShen: ['水', '金', '木'], expectedJiShen: ['土', '火'], difficulty: '进阶', notes: '壬癸日主，亥子丑水局全，水势润下，智巧之格' },
  { caseId: 'P11-C067', name: '渊海子平·润下格古例2', sourceClassic: '渊海子平', fourPillars: { year: { gan: '癸', zhi: '亥' }, month: { gan: '壬', zhi: '子' }, day: { gan: '癸', zhi: '申' }, hour: { gan: '辛', zhi: '酉' } }, dayGanWuxing: '水', monthZhiWuxing: '水', count: { '木': 0, '火': 0, '土': 0, '金': 2, '水': 6 }, dayStrength: 3, dayRootCount: 3, expectedGeju: { category: 'zhuanwang', name: '专旺-润下格（水专旺）', confidence: 0.95 }, expectedYongShen: ['水', '金', '木'], expectedJiShen: ['土', '火'], difficulty: '高阶' },
  { caseId: 'P11-C068', name: '三命通会·天元一气古例1', sourceClassic: '三命通会', fourPillars: { year: { gan: '甲', zhi: '子' }, month: { gan: '甲', zhi: '寅' }, day: { gan: '甲', zhi: '辰' }, hour: { gan: '甲', zhi: '戌' } }, dayGanWuxing: '木', monthZhiWuxing: '木', count: { '木': 5, '火': 0, '土': 2, '金': 0, '水': 1 }, dayStrength: 3, dayRootCount: 3, expectedGeju: { category: 'yiqi', name: '一气-天元一气', confidence: 0.95 }, expectedYongShen: ['木', '火'], expectedJiShen: ['金'], difficulty: '进阶', notes: '四干皆甲木，天元一气，清贵之格' },
  { caseId: 'P11-C069', name: '渊海子平·天元一气古例2', sourceClassic: '渊海子平', fourPillars: { year: { gan: '庚', zhi: '辰' }, month: { gan: '庚', zhi: '申' }, day: { gan: '庚', zhi: '戌' }, hour: { gan: '庚', zhi: '子' } }, dayGanWuxing: '金', monthZhiWuxing: '金', count: { '木': 0, '火': 0, '土': 2, '金': 5, '水': 1 }, dayStrength: 3, dayRootCount: 3, expectedGeju: { category: 'yiqi', name: '一气-天元一气', confidence: 0.95 }, expectedYongShen: ['金', '水'], expectedJiShen: ['火'], difficulty: '进阶' },
  { caseId: 'P11-C070', name: '滴天髓·地元一气古例1', sourceClassic: '滴天髓', fourPillars: { year: { gan: '甲', zhi: '寅' }, month: { gan: '丙', zhi: '寅' }, day: { gan: '戊', zhi: '寅' }, hour: { gan: '庚', zhi: '寅' } }, dayGanWuxing: '土', monthZhiWuxing: '木', count: { '木': 5, '火': 1, '土': 1, '金': 1, '水': 0 }, dayStrength: -1, dayRootCount: 0, expectedGeju: { category: 'yiqi', name: '一气-地元一气', confidence: 0.9 }, expectedYongShen: ['火', '土'], expectedJiShen: ['木', '金'], difficulty: '高阶', notes: '四支皆寅木，地元一气，厚富之格' },
  { caseId: 'P11-C071', name: '御定子平·地元一气古例2', sourceClassic: '御定子平', fourPillars: { year: { gan: '丁', zhi: '酉' }, month: { gan: '己', zhi: '酉' }, day: { gan: '辛', zhi: '酉' }, hour: { gan: '癸', zhi: '酉' } }, dayGanWuxing: '金', monthZhiWuxing: '金', count: { '木': 0, '火': 1, '土': 1, '金': 5, '水': 1 }, dayStrength: 3, dayRootCount: 4, expectedGeju: { category: 'yiqi', name: '一气-地元一气', confidence: 0.95 }, expectedYongShen: ['金', '水'], expectedJiShen: ['火'], difficulty: '高阶' },
  { caseId: 'P11-C072', name: '滴天髓·甲己化土古例1', sourceClassic: '滴天髓', fourPillars: { year: { gan: '甲', zhi: '辰' }, month: { gan: '己', zhi: '丑' }, day: { gan: '己', zhi: '未' }, hour: { gan: '甲', zhi: '戌' } }, dayGanWuxing: '土', monthZhiWuxing: '土', count: { '木': 2, '火': 0, '土': 5, '金': 1, '水': 0 }, dayStrength: 1, dayRootCount: 1, expectedGeju: { category: 'huaqi', name: '化气-甲己化土', confidence: 0.88 }, expectedYongShen: ['土', '火'], expectedJiShen: ['木'], difficulty: '进阶', notes: '甲己天干齐全，月令辰戌丑未土旺，化土格' },
  { caseId: 'P11-C073', name: '子平真诠·甲己化土古例2', sourceClassic: '子平真诠', fourPillars: { year: { gan: '己', zhi: '巳' }, month: { gan: '甲', zhi: '午' }, day: { gan: '甲', zhi: '戌' }, hour: { gan: '己', zhi: '未' } }, dayGanWuxing: '木', monthZhiWuxing: '火', count: { '木': 2, '火': 2, '土': 3, '金': 1, '水': 0 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'huaqi', name: '化气-甲己化土', confidence: 0.82 }, expectedYongShen: ['土', '火'], expectedJiShen: ['木'], difficulty: '高阶' },
  { caseId: 'P11-C074', name: '三命通会·乙庚化金古例1', sourceClassic: '三命通会', fourPillars: { year: { gan: '乙', zhi: '申' }, month: { gan: '庚', zhi: '酉' }, day: { gan: '庚', zhi: '戌' }, hour: { gan: '乙', zhi: '辰' } }, dayGanWuxing: '金', monthZhiWuxing: '金', count: { '木': 2, '火': 0, '土': 2, '金': 4, '水': 0 }, dayStrength: 1, dayRootCount: 2, expectedGeju: { category: 'huaqi', name: '化气-乙庚化金', confidence: 0.9 }, expectedYongShen: ['金', '土'], expectedJiShen: ['火'], difficulty: '进阶', notes: '乙庚天干齐全，月令申酉金旺，化金格' },
  { caseId: 'P11-C075', name: '穷通宝鉴·乙庚化金古例2', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '庚', zhi: '丑' }, month: { gan: '乙', zhi: '辰' }, day: { gan: '乙', zhi: '酉' }, hour: { gan: '庚', zhi: '申' } }, dayGanWuxing: '木', monthZhiWuxing: '土', count: { '木': 3, '火': 0, '土': 2, '金': 3, '水': 0 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'huaqi', name: '化气-乙庚化金', confidence: 0.85 }, expectedYongShen: ['金', '土'], expectedJiShen: ['火'], difficulty: '高阶' },
  { caseId: 'P11-C076', name: '滴天髓·丙辛化水古例1', sourceClassic: '滴天髓', fourPillars: { year: { gan: '丙', zhi: '申' }, month: { gan: '辛', zhi: '亥' }, day: { gan: '辛', zhi: '子' }, hour: { gan: '丙', zhi: '辰' } }, dayGanWuxing: '金', monthZhiWuxing: '水', count: { '木': 1, '火': 2, '土': 1, '金': 2, '水': 2 }, dayStrength: 0, dayRootCount: 0, expectedGeju: { category: 'huaqi', name: '化气-丙辛化水', confidence: 0.88 }, expectedYongShen: ['水', '金'], expectedJiShen: ['土'], difficulty: '进阶', notes: '丙辛天干齐全，月令亥子水旺，化水格' },
  { caseId: 'P11-C077', name: '御定子平·丙辛化水古例2', sourceClassic: '御定子平', fourPillars: { year: { gan: '辛', zhi: '子' }, month: { gan: '丙', zhi: '申' }, day: { gan: '丙', zhi: '申' }, hour: { gan: '辛', zhi: '酉' } }, dayGanWuxing: '火', monthZhiWuxing: '金', count: { '木': 0, '火': 2, '土': 0, '金': 4, '水': 2 }, dayStrength: 0, dayRootCount: 0, expectedGeju: { category: 'huaqi', name: '化气-丙辛化水', confidence: 0.85 }, expectedYongShen: ['水', '金'], expectedJiShen: ['土'], difficulty: '高阶' },
  { caseId: 'P11-C078', name: '子平真诠·丁壬化木古例1', sourceClassic: '子平真诠', fourPillars: { year: { gan: '丁', zhi: '寅' }, month: { gan: '壬', zhi: '卯' }, day: { gan: '壬', zhi: '亥' }, hour: { gan: '丁', zhi: '未' } }, dayGanWuxing: '水', monthZhiWuxing: '木', count: { '木': 4, '火': 2, '土': 1, '金': 0, '水': 1 }, dayStrength: 0, dayRootCount: 0, expectedGeju: { category: 'huaqi', name: '化气-丁壬化木', confidence: 0.9 }, expectedYongShen: ['木', '水'], expectedJiShen: ['金'], difficulty: '进阶', notes: '丁壬天干齐全，月令寅卯木旺，化木格' },
  { caseId: 'P11-C079', name: '三命通会·丁壬化木古例2', sourceClassic: '三命通会', fourPillars: { year: { gan: '壬', zhi: '亥' }, month: { gan: '丁', zhi: '寅' }, day: { gan: '丁', zhi: '卯' }, hour: { gan: '壬', zhi: '辰' } }, dayGanWuxing: '火', monthZhiWuxing: '木', count: { '木': 4, '火': 2, '土': 1, '金': 0, '水': 1 }, dayStrength: 0, dayRootCount: 0, expectedGeju: { category: 'huaqi', name: '化气-丁壬化木', confidence: 0.88 }, expectedYongShen: ['木', '水'], expectedJiShen: ['金'], difficulty: '高阶' },
  { caseId: 'P11-C080', name: '渊海子平·戊癸化火古例1', sourceClassic: '渊海子平', fourPillars: { year: { gan: '戊', zhi: '巳' }, month: { gan: '癸', zhi: '午' }, day: { gan: '癸', zhi: '未' }, hour: { gan: '戊', zhi: '寅' } }, dayGanWuxing: '水', monthZhiWuxing: '火', count: { '木': 1, '火': 3, '土': 3, '金': 0, '水': 1 }, dayStrength: 0, dayRootCount: 0, expectedGeju: { category: 'huaqi', name: '化气-戊癸化火', confidence: 0.88 }, expectedYongShen: ['火', '木'], expectedJiShen: ['水'], difficulty: '进阶', notes: '戊癸天干齐全，月令巳午火旺，化火格' },
  { caseId: 'P11-C081', name: '滴天髓·戊癸化火古例2', sourceClassic: '滴天髓', fourPillars: { year: { gan: '癸', zhi: '午' }, month: { gan: '戊', zhi: '巳' }, day: { gan: '戊', zhi: '寅' }, hour: { gan: '癸', zhi: '戌' } }, dayGanWuxing: '土', monthZhiWuxing: '火', count: { '木': 1, '火': 3, '土': 3, '金': 0, '水': 1 }, dayStrength: 1, dayRootCount: 1, expectedGeju: { category: 'huaqi', name: '化气-戊癸化火', confidence: 0.85 }, expectedYongShen: ['火', '木'], expectedJiShen: ['水'], difficulty: '高阶' },
  { caseId: 'P11-C082', name: '穷通宝鉴·冬月调候古例1', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '癸', zhi: '亥' }, month: { gan: '癸', zhi: '子' }, day: { gan: '乙', zhi: '丑' }, hour: { gan: '癸', zhi: '亥' } }, dayGanWuxing: '木', monthZhiWuxing: '水', count: { '木': 2, '火': 0, '土': 1, '金': 0, '水': 5 }, dayStrength: 0, dayRootCount: 1, isWinterBorn: true, expectedGeju: { category: 'tiaohou', name: '调候格', confidence: 0.92 }, expectedYongShen: ['火', '土'], expectedJiShen: ['水', '金'], difficulty: '入门', notes: '亥子丑月，金寒水冷木凋，无丙火暖局，调候需求极强' },
  { caseId: 'P11-C083', name: '滴天髓·冬月调候古例2', sourceClassic: '滴天髓', fourPillars: { year: { gan: '己', zhi: '丑' }, month: { gan: '丙', zhi: '子' }, day: { gan: '辛', zhi: '亥' }, hour: { gan: '庚', zhi: '申' } }, dayGanWuxing: '金', monthZhiWuxing: '水', count: { '木': 0, '火': 1, '土': 1, '金': 3, '水': 3 }, dayStrength: 0, dayRootCount: 2, isWinterBorn: true, expectedGeju: { category: 'tiaohou', name: '调候格', confidence: 0.88 }, expectedYongShen: ['火', '土'], expectedJiShen: ['水', '金'], difficulty: '进阶' },
  { caseId: 'P11-C084', name: '子平真诠·冬月调候古例3', sourceClassic: '子平真诠', fourPillars: { year: { gan: '辛', zhi: '亥' }, month: { gan: '己', zhi: '丑' }, day: { gan: '癸', zhi: '子' }, hour: { gan: '壬', zhi: '申' } }, dayGanWuxing: '水', monthZhiWuxing: '土', count: { '木': 0, '火': 0, '土': 2, '金': 2, '水': 4 }, dayStrength: 2, dayRootCount: 3, isWinterBorn: true, expectedGeju: { category: 'tiaohou', name: '调候格', confidence: 0.95 }, expectedYongShen: ['火'], expectedJiShen: ['水', '金'], difficulty: '进阶' },
  { caseId: 'P11-C085', name: '三命通会·冬月调候古例4', sourceClassic: '三命通会', fourPillars: { year: { gan: '壬', zhi: '子' }, month: { gan: '癸', zhi: '亥' }, day: { gan: '甲', zhi: '戌' }, hour: { gan: '乙', zhi: '丑' } }, dayGanWuxing: '木', monthZhiWuxing: '水', count: { '木': 3, '火': 0, '土': 2, '金': 0, '水': 3 }, dayStrength: 0, dayRootCount: 1, isWinterBorn: true, expectedGeju: { category: 'tiaohou', name: '调候格', confidence: 0.9 }, expectedYongShen: ['火', '土'], expectedJiShen: ['水'], difficulty: '进阶' },
  { caseId: 'P11-C086', name: '御定子平·冬月调候古例5', sourceClassic: '御定子平', fourPillars: { year: { gan: '戊', zhi: '子' }, month: { gan: '甲', zhi: '寅' }, day: { gan: '戊', zhi: '辰' }, hour: { gan: '癸', zhi: '亥' } }, dayGanWuxing: '土', monthZhiWuxing: '木', count: { '木': 3, '火': 0, '土': 3, '金': 0, '水': 2 }, dayStrength: 0, dayRootCount: 2, isWinterBorn: true, expectedGeju: { category: 'tiaohou', name: '调候格', confidence: 0.85 }, expectedYongShen: ['火', '木'], expectedJiShen: ['水', '金'], difficulty: '高阶' },
  { caseId: 'P11-C087', name: '穷通宝鉴·夏月调候古例1', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '丙', zhi: '巳' }, month: { gan: '丙', zhi: '午' }, day: { gan: '丁', zhi: '未' }, hour: { gan: '乙', zhi: '巳' } }, dayGanWuxing: '火', monthZhiWuxing: '火', count: { '木': 2, '火': 5, '土': 1, '金': 0, '水': 0 }, dayStrength: 3, dayRootCount: 2, isSummerBorn: true, expectedGeju: { category: 'tiaohou', name: '调候格', confidence: 0.95 }, expectedYongShen: ['水', '金'], expectedJiShen: ['火', '木'], difficulty: '入门', notes: '巳午未月，火炎土燥，无水润局，调候为急' },
  { caseId: 'P11-C088', name: '滴天髓·夏月调候古例2', sourceClassic: '滴天髓', fourPillars: { year: { gan: '戊', zhi: '午' }, month: { gan: '丁', zhi: '巳' }, day: { gan: '己', zhi: '未' }, hour: { gan: '甲', zhi: '戌' } }, dayGanWuxing: '土', monthZhiWuxing: '火', count: { '木': 2, '火': 3, '土': 3, '金': 0, '水': 0 }, dayStrength: 2, dayRootCount: 2, isSummerBorn: true, expectedGeju: { category: 'tiaohou', name: '调候格', confidence: 0.92 }, expectedYongShen: ['水', '金'], expectedJiShen: ['火', '木'], difficulty: '进阶' },
  { caseId: 'P11-C089', name: '渊海子平·夏月调候古例3', sourceClassic: '渊海子平', fourPillars: { year: { gan: '丁', zhi: '未' }, month: { gan: '丙', zhi: '午' }, day: { gan: '乙', zhi: '巳' }, hour: { gan: '辛', zhi: '巳' } }, dayGanWuxing: '木', monthZhiWuxing: '火', count: { '木': 3, '火': 4, '土': 1, '金': 0, '水': 0 }, dayStrength: 1, dayRootCount: 1, isSummerBorn: true, expectedGeju: { category: 'tiaohou', name: '调候格', confidence: 0.9 }, expectedYongShen: ['水'], expectedJiShen: ['火', '木'], difficulty: '进阶' },
  { caseId: 'P11-C090', name: '三命通会·夏月调候古例4', sourceClassic: '三命通会', fourPillars: { year: { gan: '甲', zhi: '午' }, month: { gan: '庚', zhi: '午' }, day: { gan: '丙', zhi: '戌' }, hour: { gan: '丁', zhi: '未' } }, dayGanWuxing: '火', monthZhiWuxing: '火', count: { '木': 2, '火': 4, '土': 2, '金': 0, '水': 0 }, dayStrength: 3, dayRootCount: 2, isSummerBorn: true, expectedGeju: { category: 'tiaohou', name: '调候格', confidence: 0.93 }, expectedYongShen: ['水', '金'], expectedJiShen: ['火', '木'], difficulty: '进阶' },
  { caseId: 'P11-C091', name: '神峰通考·夏月调候古例5', sourceClassic: '神峰通考', fourPillars: { year: { gan: '己', zhi: '巳' }, month: { gan: '辛', zhi: '未' }, day: { gan: '癸', zhi: '午' }, hour: { gan: '壬', zhi: '申' } }, dayGanWuxing: '水', monthZhiWuxing: '土', count: { '木': 0, '火': 3, '土': 2, '金': 2, '水': 1 }, dayStrength: -1, dayRootCount: 0, isSummerBorn: true, expectedGeju: { category: 'tiaohou', name: '调候格', confidence: 0.85 }, expectedYongShen: ['水', '金'], expectedJiShen: ['火', '土'], difficulty: '高阶' },
  { caseId: 'P11-C092', name: '滴天髓·病药格古例1', sourceClassic: '滴天髓', fourPillars: { year: { gan: '甲', zhi: '寅' }, month: { gan: '乙', zhi: '卯' }, day: { gan: '甲', zhi: '午' }, hour: { gan: '甲', zhi: '辰' } }, dayGanWuxing: '木', monthZhiWuxing: '木', count: { '木': 6, '火': 1, '土': 1, '金': 0, '水': 0 }, dayStrength: 3, dayRootCount: 4, expectedGeju: { category: 'bingyao', name: '病药格', confidence: 0.75 }, expectedYongShen: ['金', '土', '火'], expectedJiShen: ['木', '水'], difficulty: '进阶', notes: '病神：木太旺(75%)；药神：金克、火泄、土耗' },
  { caseId: 'P11-C093', name: '子平真诠·病药格古例2', sourceClassic: '子平真诠', fourPillars: { year: { gan: '庚', zhi: '申' }, month: { gan: '庚', zhi: '酉' }, day: { gan: '辛', zhi: '巳' }, hour: { gan: '庚', zhi: '子' } }, dayGanWuxing: '金', monthZhiWuxing: '金', count: { '木': 0, '火': 2, '土': 0, '金': 5, '水': 1 }, dayStrength: 2, dayRootCount: 3, expectedGeju: { category: 'bingyao', name: '病药格', confidence: 0.78 }, expectedYongShen: ['火', '水'], expectedJiShen: ['金', '土'], difficulty: '进阶', notes: '病神：金太旺(62.5%)；药神：火克、水泄' },
  { caseId: 'P11-C094', name: '神峰通考·病药格古例3', sourceClassic: '神峰通考', fourPillars: { year: { gan: '丙', zhi: '子' }, month: { gan: '己', zhi: '巳' }, day: { gan: '己', zhi: '未' }, hour: { gan: '丁', zhi: '午' } }, dayGanWuxing: '土', monthZhiWuxing: '火', count: { '木': 0, '火': 3, '土': 4, '金': 0, '水': 1 }, dayStrength: 1, dayRootCount: 2, expectedGeju: { category: 'bingyao', name: '病药格', confidence: 0.72 }, expectedYongShen: ['木', '金', '水'], expectedJiShen: ['土', '火'], difficulty: '高阶', notes: '病神：土偏旺(50%)；药神：木克、金泄、水耗' },
  { caseId: 'P11-C095', name: '渊海子平·病药格古例4', sourceClassic: '渊海子平', fourPillars: { year: { gan: '壬', zhi: '子' }, month: { gan: '癸', zhi: '亥' }, day: { gan: '壬', zhi: '申' }, hour: { gan: '癸', zhi: '酉' } }, dayGanWuxing: '水', monthZhiWuxing: '水', count: { '木': 0, '火': 0, '土': 0, '金': 2, '水': 6 }, dayStrength: 3, dayRootCount: 4, expectedGeju: { category: 'bingyao', name: '病药格', confidence: 0.8 }, expectedYongShen: ['土', '木'], expectedJiShen: ['水', '金'], difficulty: '进阶', notes: '病神：水太旺(75%)；药神：土克、木泄' },
  { caseId: 'P11-C096', name: '三命通会·病药格古例5', sourceClassic: '三命通会', fourPillars: { year: { gan: '丙', zhi: '午' }, month: { gan: '丁', zhi: '巳' }, day: { gan: '丙', zhi: '戌' }, hour: { gan: '戊', zhi: '午' } }, dayGanWuxing: '火', monthZhiWuxing: '火', count: { '木': 0, '火': 5, '土': 2, '金': 1, '水': 0 }, dayStrength: 3, dayRootCount: 2, expectedGeju: { category: 'bingyao', name: '病药格', confidence: 0.75 }, expectedYongShen: ['水', '土', '金'], expectedJiShen: ['火', '木'], difficulty: '高阶', notes: '病神：火偏旺(62.5%)；药神：水克、土泄、金耗' },
  { caseId: 'P11-C097', name: '滴天髓·通关格古例1', sourceClassic: '滴天髓', fourPillars: { year: { gan: '庚', zhi: '申' }, month: { gan: '甲', zhi: '寅' }, day: { gan: '庚', zhi: '辰' }, hour: { gan: '甲', zhi: '寅' } }, dayGanWuxing: '金', monthZhiWuxing: '木', count: { '木': 4, '火': 0, '土': 1, '金': 3, '水': 0 }, dayStrength: 0, dayRootCount: 2, expectedGeju: { category: 'tongguan', name: '通关格', confidence: 0.8 }, expectedYongShen: ['水'], expectedJiShen: ['木', '金'], difficulty: '进阶', notes: '金木相战（各4/3），喜水通关（金→水→木顺生）' },
  { caseId: 'P11-C098', name: '子平真诠·通关格古例2', sourceClassic: '子平真诠', fourPillars: { year: { gan: '壬', zhi: '子' }, month: { gan: '丙', zhi: '午' }, day: { gan: '丙', zhi: '寅' }, hour: { gan: '壬', zhi: '申' } }, dayGanWuxing: '火', monthZhiWuxing: '火', count: { '木': 2, '火': 3, '土': 0, '金': 1, '水': 2 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'tongguan', name: '通关格', confidence: 0.78 }, expectedYongShen: ['木'], expectedJiShen: ['水', '火'], difficulty: '进阶', notes: '水火相战（各2/3），喜木通关（水→木→火顺生）' },
  { caseId: 'P11-C099', name: '三命通会·通关格古例3', sourceClassic: '三命通会', fourPillars: { year: { gan: '戊', zhi: '辰' }, month: { gan: '甲', zhi: '寅' }, day: { gan: '戊', zhi: '戌' }, hour: { gan: '甲', zhi: '寅' } }, dayGanWuxing: '土', monthZhiWuxing: '木', count: { '木': 4, '火': 0, '土': 3, '金': 1, '水': 0 }, dayStrength: 0, dayRootCount: 2, expectedGeju: { category: 'tongguan', name: '通关格', confidence: 0.75 }, expectedYongShen: ['火'], expectedJiShen: ['木', '土'], difficulty: '高阶', notes: '木土相战（各4/3），喜火通关（木→火→土顺生）' },
  { caseId: 'P11-C100', name: '渊海子平·通关格古例4', sourceClassic: '渊海子平', fourPillars: { year: { gan: '丙', zhi: '戌' }, month: { gan: '庚', zhi: '申' }, day: { gan: '丙', zhi: '午' }, hour: { gan: '庚', zhi: '寅' } }, dayGanWuxing: '火', monthZhiWuxing: '金', count: { '木': 2, '火': 3, '土': 1, '金': 2, '水': 0 }, dayStrength: 0, dayRootCount: 1, expectedGeju: { category: 'tongguan', name: '通关格', confidence: 0.72 }, expectedYongShen: ['土'], expectedJiShen: ['火', '金'], difficulty: '高阶', notes: '火金相战（各3/2），喜土通关（火→土→金顺生）' },
  { caseId: 'P11-C101', name: '神峰通考·通关格古例5', sourceClassic: '神峰通考', fourPillars: { year: { gan: '甲', zhi: '寅' }, month: { gan: '壬', zhi: '子' }, day: { gan: '戊', zhi: '辰' }, hour: { gan: '丙', zhi: '戌' } }, dayGanWuxing: '土', monthZhiWuxing: '水', count: { '木': 2, '火': 2, '土': 2, '金': 0, '水': 2 }, dayStrength: -1, dayRootCount: 1, expectedGeju: { category: 'tongguan', name: '通关格', confidence: 0.7 }, expectedYongShen: ['金'], expectedJiShen: ['土', '水'], difficulty: '高阶', notes: '土水相战（各2/2），喜金通关（土→金→水顺生）' },
  { caseId: 'P11-C102', name: '子平真诠·扶抑格·旺极古例1', sourceClassic: '子平真诠', fourPillars: { year: { gan: '甲', zhi: '寅' }, month: { gan: '乙', zhi: '卯' }, day: { gan: '甲', zhi: '午' }, hour: { gan: '丙', zhi: '寅' } }, dayGanWuxing: '木', monthZhiWuxing: '木', count: { '木': 6, '火': 2, '土': 0, '金': 0, '水': 0 }, dayStrength: 3, dayRootCount: 4, expectedGeju: { category: 'fuyi', name: '扶抑格', confidence: 0.75 }, expectedYongShen: ['金', '土', '火'], expectedJiShen: ['木', '水'], difficulty: '入门', notes: '甲木极旺(强度=3)，宜抑：金克、火泄、土耗' },
  { caseId: 'P11-C103', name: '渊海子平·扶抑格·旺极古例2', sourceClassic: '渊海子平', fourPillars: { year: { gan: '丙', zhi: '午' }, month: { gan: '丙', zhi: '巳' }, day: { gan: '丁', zhi: '未' }, hour: { gan: '甲', zhi: '辰' } }, dayGanWuxing: '火', monthZhiWuxing: '火', count: { '木': 2, '火': 5, '土': 1, '金': 0, '水': 0 }, dayStrength: 3, dayRootCount: 2, expectedGeju: { category: 'fuyi', name: '扶抑格', confidence: 0.78 }, expectedYongShen: ['水', '土', '金'], expectedJiShen: ['火', '木'], difficulty: '入门', notes: '火极旺(3)，宜抑：水克、土泄、金耗' },
  { caseId: 'P11-C104', name: '滴天髓·扶抑格·旺极古例3', sourceClassic: '滴天髓', fourPillars: { year: { gan: '庚', zhi: '申' }, month: { gan: '辛', zhi: '酉' }, day: { gan: '庚', zhi: '戌' }, hour: { gan: '己', zhi: '巳' } }, dayGanWuxing: '金', monthZhiWuxing: '金', count: { '木': 0, '火': 2, '土': 2, '金': 4, '水': 0 }, dayStrength: 2, dayRootCount: 3, expectedGeju: { category: 'fuyi', name: '扶抑格', confidence: 0.72 }, expectedYongShen: ['火', '水', '木'], expectedJiShen: ['金', '土'], difficulty: '进阶', notes: '金偏旺(2)，宜抑：火克、水泄、木耗' },
  { caseId: 'P11-C105', name: '三命通会·扶抑格·弱极古例1', sourceClassic: '三命通会', fourPillars: { year: { gan: '己', zhi: '未' }, month: { gan: '癸', zhi: '亥' }, day: { gan: '乙', zhi: '巳' }, hour: { gan: '己', zhi: '丑' } }, dayGanWuxing: '木', monthZhiWuxing: '水', count: { '木': 2, '火': 2, '土': 3, '金': 0, '水': 1 }, dayStrength: -2, dayRootCount: 1, expectedGeju: { category: 'fuyi', name: '扶抑格', confidence: 0.75 }, expectedYongShen: ['木', '水'], expectedJiShen: ['土', '金'], difficulty: '入门', notes: '乙木偏弱(-2)，宜扶：比劫木、印水' },
  { caseId: 'P11-C106', name: '穷通宝鉴·扶抑格·弱极古例2', sourceClassic: '穷通宝鉴', fourPillars: { year: { gan: '庚', zhi: '戌' }, month: { gan: '戊', zhi: '子' }, day: { gan: '丙', zhi: '申' }, hour: { gan: '己', zhi: '未' } }, dayGanWuxing: '火', monthZhiWuxing: '水', count: { '木': 0, '火': 2, '土': 3, '金': 2, '水': 1 }, dayStrength: -2, dayRootCount: 0, expectedGeju: { category: 'fuyi', name: '扶抑格', confidence: 0.72 }, expectedYongShen: ['木', '火'], expectedJiShen: ['水', '土', '金'], difficulty: '进阶', notes: '丙火弱(-2)，宜扶：木生火、火助火' },
  { caseId: 'P11-C107', name: '御定子平·扶抑格·弱极古例3', sourceClassic: '御定子平', fourPillars: { year: { gan: '乙', zhi: '酉' }, month: { gan: '庚', zhi: '申' }, day: { gan: '辛', zhi: '巳' }, hour: { gan: '丙', zhi: '寅' } }, dayGanWuxing: '金', monthZhiWuxing: '金', count: { '木': 2, '火': 2, '土': 1, '金': 2, '水': 1 }, dayStrength: -2, dayRootCount: 1, expectedGeju: { category: 'fuyi', name: '扶抑格', confidence: 0.7 }, expectedYongShen: ['土', '金'], expectedJiShen: ['火', '木'], difficulty: '进阶', notes: '辛金偏弱(-2)，宜扶：土生金、金助金' },
  { caseId: 'P11-C108', name: '千里命稿·扶抑格·弱极古例4', sourceClassic: '千里命稿', fourPillars: { year: { gan: '癸', zhi: '未' }, month: { gan: '丙', zhi: '午' }, day: { gan: '己', zhi: '酉' }, hour: { gan: '甲', zhi: '戌' } }, dayGanWuxing: '土', monthZhiWuxing: '火', count: { '木': 2, '火': 2, '土': 2, '金': 1, '水': 1 }, dayStrength: -2, dayRootCount: 1, expectedGeju: { category: 'fuyi', name: '扶抑格', confidence: 0.68 }, expectedYongShen: ['火', '土'], expectedJiShen: ['木', '水', '金'], difficulty: '高阶', notes: '己土偏弱(-2)，宜扶：火生土、土助土' },
]

export class GejuCaseDB {
  private db: PatternCase[]

  constructor(data?: PatternCase[]) {
    this.db = data ?? CASES_DB
  }

  all(): PatternCase[] {
    return this.db.slice()
  }

  byCategory(category: string): PatternCase[] {
    return this.db.filter(c => c.expectedGeju.category === category)
  }

  byId(id: string): PatternCase | undefined {
    return this.db.find(c => c.caseId === id)
  }

  byDifficulty(d: string): PatternCase[] {
    return this.db.filter(c => c.difficulty === d)
  }

  getCaseCount(): number {
    return this.db.length
  }
}

export const defaultGejuCaseDB = new GejuCaseDB()

export { CASES_DB }
